gemrb/plugins/SDLVideo/SDL20Video.cpp, gemrb/plugins/SDLVideo/SDLVideo.h
Trying to bring the SDL2 version up and above the SDL1 version:
- now uses windowed fullscreen, using SDL2's own scaling
- window can be resized, also using SDL2's own scaling
- cursor trails gone
=> Sdl2 hacking

gemrb/core/GUI/GameControl.cpp, gemrb/core/GUI/GameControl.h
when SDL2 scales the window to a different aspect ratio, it will pad
sides with black.
Since mouse cursor position was passed unsigned, the negative x and/or y
values generated when in the left and/or top padded areas was wrapped,
and scrolling went the wrong way.
=> Fix "reverse" scroll in SDL2 when too tall or wide

gemrb/plugins/SDLVideo/SDL20Video.cpp
SDL_SetSurfaceBlendMode needs to be SDL_BLENDMODE_BLEND on the surface
in order for it to, well, blend.
=> set blend mode in SetSurfaceAlpha

gemrb/GUIScripts/iwd2/Skills.py
When creating a new PC, there were more skill points available than there were supposed to be.
This changes the partial formula from:
(class pts + human pts + int bonus pts) * 4
to:
(class pts + human pts) * 2 + int bonus pts * 4
This returns values equal to the original game.
=> IWD2::CG: adjusts skill points calculation

gemrb/plugins/SDLVideo/SDL20Video.cpp
The way the SDL2 code handles keypresses and so on interacts in some weird ways with the rest of the system. It is a bit muddled, I think, because so much is "shared" between the SDL1 and SDL2 paths (through SDLVideo), even when they way of doing things in SDL2 does not neatly map to SDL1.
This fixes the problems of strange/double input in text fields, and the fact that neither the console nor fullscreen could be toggled through keypresses ingame.
=> Sdl2 input hacking

gemrb/GUIScripts/iwd2/Skills.py
The empty item line at the bottom is gone. In addition, this saves a Python exception.
`TopIndex` is used around the object without checking whether we should really go there by scrolling down.
Behaves a little more like IWD2, where you can move the scrollbar at the bottom parts without any updates.
=> IWD2::Skills: prevents scrolling beyond skill items

gemrb/core/System/String.cpp
If `String` aliases to `std::wstring`, `::length` returns the number
of wide-chars, not bytes. For the worst case, we should allow each
`wchar_t` to be mapped into space not smaller, shrinking the space after
the result of `wcstombs`.
Otherwise, multibyte charachters make the resulting string cut-off
early.
As I'm tracking down the problem that German IWD2-PC-sound files containing umlaut-chars are not displayed correctly and played in CG (`ResourceManager` can't find them), I noticed that that the path `Kämpfer_männlich_1` (=`fighter_male_1`) in `TextBox::QueryText` contains 20 *chars*, effectively writes `KÃ¤MPFER_MÃ¤NNLI` (20 *bytes* mb-string) to Python. Although lost in encoding, this patch fixes the behaviour to return at least the fully-sized but still useless string …
=> String: extends buffer in `MBCStringFromString'

gemrb/plugins/SDLVideo/SDL20Video.cpp
If not using touch input,
SDL_MOUSEMOTION/SDL_MOUSEBUTTONDOWN/SDL_MOUSEBUTTONUP would never break,
instead moving on to SDL_KEYDOWN -- which would read
event.key.keysym.scancode and erronously break on the scancode event
read when RMB+MouseMovement occurred, never moving on to return the
event to SDLVideoDriver::ProcessEvent . We now explicitly return the
event when event.button.which is not SDL_TOUCH_MOUSEID .
=> SDL2: Fix RMB stuck cursor

gemrb/GUIScripts/GUIClasses.py, gemrb/core/GUI/EventMgr.cpp, gemrb/core/GUI/Window.cpp, gemrb/core/GUI/Window.h, gemrb/plugins/GUIScript/GUIScript.cpp, gemrb/plugins/GUIScript/PythonHelpers.cpp, gemrb/plugins/GUIScript/PythonHelpers.h
One thing I'm really missing is changing PCs (in the inventory window) by pressing keys 1-6.
I did some research but did not find a way to have a flexible way to customize key stroke events outside of controls (i.e. do the actual logic in Python). Callbacks are limited to controls and certain events so far.
This PR allows scripts to make use of reading pressed keys on the unspecified window level and to act on them. If you think this is a good idea, we can do something like this to solve the inventory issue: https://github.com/MarcelHB/gemrb/compare/window_keys...MarcelHB:inventory_pc_key?expand=1
=> GUIScript: allows callbacks for window-scoped key presses

gemrb/GUIScripts/LevelUp.py
The LevelUp code does several checks to make sure that only
the relevant ability windows are opened.
One of these checks is about spell selection. If the character class
has a MageTable, then a loop counts the difference in spell count
for each spell level and if there are new spells known, the spell
selection window is opened.
The problem is that for sorcerers it checks the MXSPLSRC table
which is how many spells the character can cast and not the proper
table which is SPLSRCKN and defines how many spells the character knows.
So, when a sorcerer levels up to a level that doesn't grant additional
known spells but grants more spell castings per day, the spell selection
window is opened but there are no spells to be selected and the leveling
process is stuck.
The code is modified to check …
=> OpenLevelUpWindow: Fix Sorcerer LevelUp

gemrb/GUIScripts/GUICommonWindows.py, gemrb/GUIScripts/GUIREC.py, gemrb/GUIScripts/bg1/GUIINV.py, gemrb/GUIScripts/iwd2/GUIINV.py, gemrb/GUIScripts/iwd2/GUIREC.py, gemrb/GUIScripts/iwd2/GUISPL.py, gemrb/core/Game.cpp
Ok, as you suggested in #53, I did some minor modifications to the code. In IWD2, everything works well.
I tried BG1 and managed to get the same work for `GUIINV` and `GUIREC`. In contrast, `GUIMG` and `GUIPR` fail as there is something inside the Python scripts shaking `last_win_focused` to set the options window focused, not the desired center window. If you enter such a GUI on a PC that can actually cast spells, it works until reaching a PC with a grayed window.
I tried some things but this is a little beyond what I'm trying to focus on right now. So I skipped that for now.
=> GUIScripts::IWD2: navigation among PCs inside GUIs

gemrb/plugins/SDLVideo/SDL20Video.cpp
use it as a function not as a function pointer
causes gcc 5.1 warning: error: ordered comparison of pointer with integer zero [-Werror=extra]
=> fix incorrect usage of SDL_GetNumTouchDevices

README
Old link was redirecting to forums home page instead of specific forum for GemRB.
=> Fix link to forum

gemrb/plugins/ACMReader/unpacker.cpp
Minor nerdy things:
I attempt to put my build setup somewhere else. There I have a GCC v7.2.0 on x86_64 and after setup, IWD2 crashes right at the moment of loading menu music.
The error can be tracked down to this very line: the author once wanted to fill a ptr-wide buffer full of 0xF bytes, shift them aside and add the result to `buff_middle`. This certainly works on 32bit and surprinsingly my VBox Linux, but here `-1ul` evaluates to `0x00000000FFFFFFFF` for this op. The shifted bit pattern will then throw the pointer far away.
=> ACMReader: fixes underflow on pointer magic

gemrb/plugins/SDLVideo/SDL20GLVideo.cpp, gemrb/plugins/SDLVideo/Shaders/SpritePal.glslf, gemrb/plugins/SDLVideo/Shaders/SpritePalGrayed.glslf, gemrb/plugins/SDLVideo/Shaders/SpritePalSepia.glslf
There are some minor but annoying rendering issues when using OpenGL:
1. Mysterious black pixels in the snow. Blending on area tiles is enabled even if there is no reason to (as of the docs, tiles contain no alpha-values and `BLIT_HALFTRANS` isn't set here), so I set blending to opaque for the area background.
2. Char shadows are opaque and item piles are always outlined. Both these issues are half-related since there is no support on `BLIT_NOSHADOW` and `BLIT_TRANSSHADOW`. I put this handling to the fragment shaders - my experience in GLSL is limited, but they are ES compliant and for now, they work. ;)
3. Ground circles are mostly missing (see the piece of green circle close to the goblin at the center?) and ground reticles lack the outer bound. Something is messed up around scissoring, …
=> OpenGL: some fixes

gemrb/plugins/SDLVideo/SDL20GLVideo.h
In #63 I missed adding `SDL20GLVideo.h` so the `OPENGL_BACKEND=OpenGL` setup won't compile. CI is probably not building that. :grin:
=> OpenGL: adds missing header update

gemrb/plugins/SDLVideo/GLPaletteManager.cpp
On OpenGL, some texts look close to illegible:
The code did only unset full-transparent pixels when it should unset anything but `0xFF` for keyed palettes. But then we can also save instructions and failing branch predictions for this check completely.
Magic effects still look the same (and some a little dark).
=> OpenGL: better text rendering

gemrb/GUIScripts/GUICommonWindows.py, gemrb/GUIScripts/GUIMA.py, gemrb/GUIScripts/iwd2/GUIINV.py
Contrary to other games, the globe-clock is visible nearly everywhere and its control ID was wrong so there is no natural way to retrieve the time by tooltip (and at all?). 
It actually moves in map overview and inventory - and as in the original, if you click it in the inventory, the puppet stops moving. :+1:
=> GUIScripts: the clock in IWD2

gemrb/core/Interface.cpp, gemrb/core/Video.h, gemrb/plugins/SDLVideo/SDL20GLVideo.cpp, gemrb/plugins/SDLVideo/SDL20GLVideo.h, gemrb/plugins/SDLVideo/SDLVideo.h
There is one problem where GUI drawing and OpenGL bite each other: screen areas that are not redrawn inside a frame only redraw the cursor into the back buffer. For the cursor movements, this produces tons of artifacts on the background of overlaying windows or modals. For modals, thanks to double buffering, we have a some nauseaing 15Hz flickering in addition (one grayed background and the previous one without gray tone).
For OpenGL, for now I propose to create a texture of everything that has been drawn to the background the last time before we create a modal or put a window on top. A suspended window then isn't really redrawn but just the top-most active window(s) on top of the screenshot of the disabled ones.
This isn't perfect yet: e. g. I cannot remove a cursor that sticks on an …
=> OpenGL: no more flickering on overlays

gemrb/plugins/SDLVideo/GLPaletteManager.cpp, gemrb/plugins/SDLVideo/GLPaletteManager.h, gemrb/plugins/SDLVideo/GLTextureSprite2D.cpp, gemrb/plugins/SDLVideo/SDL20GLVideo.cpp
In #63 , I tried to fix "mysterious black pixels on snow" for OpenGL. This fix was very rough, it breaks BG water rendering.
Not that bad, this way I discovered some more general bug as `0` has been treated as invalid palette index for OpenGL. But since this is the default color key index for transparency, by default, for every paletted texture, the pixels of color index `0` are then discarded regardless of intended transparency.
=> OpenGL: fix for map tile rendering

gemrb/plugins/OpenALAudio/OpenALAudio.cpp, gemrb/plugins/OpenALAudio/OpenALAudio.h
Maybe it's a more subjective issue, but let's consider the chanting dudes in this screenshot below:
When centering through them when their samples are playing, inside the inner rectangle you have a very loud sound with very little fade-in, and each red line immediately flips one source (on stereo) from one speaker to the other one. This feels very unbalanced.
On OpenAL, the listener's position is ground (`{ x, y, 0 }`) as all sources are. I propose to put it to the camera (height!), so it has a longer fade-in/out and less amplitude right above. Values `< 100` don't address the impression well, `> 200` makes sounds too low.
Feel free to try it and propose something else, but I consider `0` a bad choice. For distance calculations I think it's Ok to leave it as-is.
Other addressed examples …
=> OpenAL: z-axis for listener

gemrb/plugins/AREImporter/AREImporter.cpp
When saving an IWD2 game in GemRB, loading the game into the original game reveals an interesting issue: you cannot enter buildings anymore. Doors open correctly and the cursor shows a trigger, but nothing actually happens.
I diffed the ARE files on triggers and found a significant difference: The "alternative use point" in IESDP claims that there are two words used for x/y coords. Actually, in 9.1 AREs, these 4 bytes are unused, and instead it makes use of two dwords right behind that in the *unknown* region.
Then, I made IWD2 both read and write into these regions in addition. It's a little workaround on the lower two bytes since x/y coords are `short`s internally and I better don't simply touch that now.
Anyway, now we can better cross-play as far as I have advanced, which makes …
=> IWD2: savegame compatibility fix

gemrb/core/ControlAnimation.cpp, gemrb/core/ControlAnimation.h
When playing IWD2 and hitting Pause, then changing into the inventory, the paperdoll's palette is never adjusted, so we see this standing frozen:
`UpdateAnimation` will always either skip updating or proceed in frames, which is both not fully what is useful here. I reworked that a little in a way that `SetPaletteGradients` will cause redraw without continuing the animation.
The whole thing has some annoying design, but at least this will stop rainbow colours here.
=> ControlAnimation: palette updates on pause

gemrb/core/Polygon.cpp, gemrb/plugins/FXOpcodes/FXOpcodes.cpp
This keyword has no real meaningful impact anymore and causes issues
when compiling under newer versions of the C++ standard.
=> remove 'register' keyword

gemrb/core/PluginLoader.cpp, gemrb/core/System/VFS.cpp
Tried to build and run on 64-bit Windows, had to change a couple lines that assumed 32-bit. Also strtok was called with a wrong constant.
=> Win64 fixes for finding files and making directories

gemrb/core/PluginLoader.cpp
Hey,
I just tried to build the most recet `HEAD` on my Windows with GCC v9.1 and encountered the following errors:
```
./gemrb/core/PluginLoader.cpp: In function 'void GemRB::LoadPlugins(char*)':
./gemrb/core/PluginLoader.cpp:89:73: error: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'GemRB::Version_t' {aka 'const char* (*)()'} [-Werror=cast-function-type]
89 | #define GET_PLUGIN_SYMBOL( handle, name )  GetProcAddress( handle, name )
|                                                                         ^
./gemrb/core/PluginLoader.cpp:197:40: note: in expansion of macro 'GET_PLUGIN_SYMBOL'
197 |   Version_t LibVersion = ( Version_t ) GET_PLUGIN_SYMBOL( hMod, "GemRBPlugin_Version" );
|                                        ^~~~~~~~~~~~~~~~~ …
```
=> PluginLoader: fixes compiler errors for GCC and Win

gemrb/core/GUI/Console.cpp, gemrb/core/GUI/Console.h, gemrb/core/Interface.cpp, gemrb/core/Interface.h, gemrb/plugins/SDLVideo/SDL20Video.cpp
Thought I'd pick something from the issue list again.
I did some minmal decoupling in order to let `Interface` be the one that moves the clipboard text to whatever it considers appropriate -- the console only so far.
Tested successfully on Windows and Linux.
Closes #154
=> SDL2: enables pasting of text into console

gemrb/core/CharAnimations.cpp, gemrb/core/CharAnimations.h, gemrb/core/Scriptable/Actor.cpp, gemrb/core/Scriptable/Actor.h
Please check if this is what we were talking about in #123, and why I was hestitating to reuse `DrawActorSprite` for this purpose: It always uses a ragdoll palette for drawing - even if we pass different animations to it, so I prefer not to touch that so much and use a different path.
Closes #123
=> Actor animation: shadow palette

gemrb/core/GameScript/GSUtils.cpp, gemrb/core/Scriptable/Actor.cpp, gemrb/core/Scriptable/Actor.h, gemrb/core/Scriptable/Scriptable.cpp, gemrb/core/Scriptable/Scriptable.h
This covers many cases when the original games indicate the sound emitting actor by a pulsating white circle, essentially most of the time when there is a verbal constant requested but also existence sounds. I have bound it to the time of the sound file (presumably) playing, without looking for cases of early interruption -- if you know some, I can try to implement them.
The animation was no exact rocket science but it's the numbers that really make it look like in BG1.
Closes #159
=> Talking circles

gemrb/core/Map.cpp, gemrb/core/Map.h, gemrb/plugins/AREImporter/AREImporter.cpp, gemrb/plugins/AREImporter/AREImporter.h
That's what we've synthesized in #163, it fixes every major map animation annoyance for PST. There is probably details left, like this one that I cannot explain yet, but you probably don't even notice unless playing side by side:
Closes #163
=> Map: statically adjusting some animation flags for PST

gemrb/core/CharAnimations.cpp, gemrb/core/CharAnimations.h, gemrb/core/Palette.cpp, gemrb/core/Palette.h
This fixes:
- PST: Grace, Ebb and some guards having overall bad animation colors.
- BG2: Umber hulks and fire giants having bad attack animation colors.
- IWD: Arundel and some colorfully misplaced pixels.
Closes #168
By the way, the PR template is not taking effect yet!
=> CharAnimations: palette update

gemrb/core/CharAnimations.cpp
In BG, I had some random encounter with Gnolls or Flinds that make the game fatally exit over `Palette is supposed to be named, but got no name!`. Fixes behaviour introduced by #181.
Should have been that way at first place I guess, but I did not correctly check the cases of the destructor of `CharAnimations`.
=> CharAnimations: fixes missing palette resref on stance change

gemrb/core/Map.h
I'm not fully sure what you meant by "fallback" exactly - I inserted a question mark for that case - since I did not really see where this bubbles through at the end of PST since it's actually loaded into the game but just not updated in the string table.
Closes #185
=> Map: prevents crash if map note has encoding issues

gemrb/core/CharAnimations.cpp
See #190. `SetupColors` has a side-effect of replacing the animation palette again using `FreePalette` after the recently updated (stance changed) palette. In case of the related issue, an unrelated `PaletteResRef` name may be still be given at that time, leading to the crash.
Closes #190
=> CharAnimations: unsets palette resref name on stance change

gemrb/plugins/SDLVideo/Pixels.h, gemrb/plugins/SDLVideo/SDL12Video.h
For GCC 9.2 and the current flag set, this code was illegal.
See #224.
=> [subviews] SDL: fixes compiler errors in SDL 1.2 code

gemrb/core/Scriptable/Actor.cpp, gemrb/unhardcoded/bg1/avatars.2da, gemrb/unhardcoded/bg2/avatars.2da, gemrb/unhardcoded/how/avatars.2da, gemrb/unhardcoded/iwd/avatars.2da, gemrb/unhardcoded/iwd2/avatars.2da
- Flying creatures like Marcel's bats from #258 and birds not having circles drawn even at maximum marker feedback. 
- above creatures are not valid for dialog anymore (#263), though they still have the talk cursor and tooltips
- tested locally
=> No circles for flying creatures & not valid for dialog

gemrb/GUIScripts/GUIWORLD.py, gemrb/core/Game.cpp
Now they are at the bottom, and BG has the action bars visually disabled, too. 
Closes #285
=> Subviews: fixing guideath position and display

gemrb/core/Game.cpp, gemrb/core/Map.cpp
Removed Fog from GetGlobalTint and GetWeather to prevent miscalculated lightness in GetLightLevel. FogTint variable was also removed due to compilation error "un-used variable" with FreeBSD clang version 6.0.1.
=> Temporary fix for issue #332

gemrb/unhardcoded/iwd/clabdrui.2da, gemrb/unhardcoded/iwd/clabpala.2da
See #356.
Non-HoW IWD only knows innate spells until SPIN125 so these values have nothing to do here. I have manually tested if upleveling between level 10 and 14 gives alternate innate spells - but there is nothing.
=> Cleanup of invalid spells in IWD clab files

gemrb/core/GUI/Button.cpp
This is more like patchwork: I guess somewhere something is changing control flags of the button while it is already its own disabled state but this does not matter for `Control::IsDisabled` when starting the action, so let's reinforce that even if the state's already there.
closes #283
=> subviews: Really disabling action bar buttons

gemrb/GUIScripts/iwd/Start.py
Otherwise, we can scroll contents of the window away horizontally since the windows are never wider than 640px (both IWD w/ + w/o HoW).
Closes #411
=> subviews: fixes width of IWD version label in main menu

gemrb/plugins/SDLVideo/SDL20Video.cpp, gemrb/plugins/SDLVideo/SDL20Video.h
I removed your other change since there is no reason IMO to keep that switch - and it did not help here.
closes #410
=> subviews: fix for properly clearing render targets in some cases

gemrb/core/Core.cpp
Adjusted calculation so the angle used starts with 0 degrees being on the positive x-axis instead of positive y-axis.
=> Feet2Pixels Correction

gemrb/core/GameScript/Actions.cpp, gemrb/core/Map.cpp, gemrb/core/Map.h, gemrb/core/Scriptable/Actor.cpp, gemrb/includes/voodooconst.h
Replaced VOODOO_SHOUT_RANGE with a call to Feet2Pixels. Also adjusted Map::Shout to accept a flag signifying if the call was from GameScript::GlobalShout or not to still allow for the unlimited shout distance of GameScript::GlobalShout.
=> replaced VOODOO_SHOUT_RANGE constant with Feet2Pixels function call

gemrb/plugins/SDLVideo/SDLVideo.cpp
This is patchwork against the crash in #554. There is some more code in SDL2 that once seemed to address fade colors, but @bradallred had put (parts of) it into comments. So I guess it makes more sense to see this working in subviews than trying to recover that in master.
Just prevent people from seeing the crash in PST right now.
=> SDLVideo: prevents a crash on screen fading under SDL2

gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h
Interestingly, `std::fill` is about as fast as that `SDL_memset4` on Linux, but only half as good on an old Windows 7 with Lynnfield CPU.
Anyway, that's more like the canonical way to have it compiling without errors (#577).
=> subviews: makes SDL v1.2 code compile on GCC again

gemrb/unhardcoded/bg1/avatars.2da
It misses a line for 0x7700 (Ghouls), so the game falls back to the ettercap animation. This adds that line, tested locally.
=> BG1 avatars.2da: Additional entry for ghouls

gemrb/plugins/SDLVideo/Pixels.h
GCC doesn't like a missing return, regardless of the `assert`:
```cpp
[ 94%] Building CXX object gemrb/plugins/TISImporter/CMakeFiles/TISImporter.dir/TISImporter.cpp.obj
In file included from ./gemrb_subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:28,
from ./gemrb_subviews/gemrb/plugins/SDLVideo/SDLVideo.h:29,
from ./gemrb_subviews/gemrb/plugins/SDLVideo/SDLVideo.cpp:21:
./gemrb_subviews/gemrb/plugins/SDLVideo/Pixels.h: In member function 'virtual Uint8 GemRB::SDLPixelIterator::Channel(Uint32, Uint8) const':
./gemrb_subviews/gemrb/plugins/SDLVideo/Pixels.h:442:2: error: control reaches end of non-void function [-Werror=return-type]
442 |  }
|  ^
```
=> SDL/Pixels: fixes a GCC compiler error

gemrb/core/Scriptable/Door.h, gemrb/core/Scriptable/Scriptable.h
Otherwise, GCC refuses to continue:
```cpp
[  2%] Building CXX object gemrb/core/CMakeFiles/gemrb_core.dir/ArchiveImporter.cpp.obj
In file included from ./gemrb_subviews/gemrb/core/Game.h:37,
from ./gemrb_subviews/gemrb/core/Animation.cpp:25:
./gemrb_subviews/gemrb/core/Scriptable/Scriptable.h:412:7: error: 'shared_ptr' in namespace 'std' does not name a template type
412 |  std::shared_ptr<Gem_Polygon> outline;
|       ^~~~~~~~~~
In file included from ./gemrb_subviews/gemrb/core/Game.h:37,
from ./gemrb_subviews/gemrb/core/Animation.cpp:25:
./gemrb_subviews/gemrb/core/Scriptable/Scriptable.h:30:1: note: 'std::shared_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
29 | #include <map>
+++ |+#include <memory>
30 |
```
``` …
```
=> [subviews] Compiler fixes

gemrb/core/Inventory.cpp
My first attempt to contribute. I've found out that depleted items are not deleted because the replacement item "Z_GEN2B.itm" is not present. as @lynxlynxlynx pointed out, it's actually a sound as PST does not use replacement items.
Issue #651
=> fix expended items not deleting

gemrb/GUIScripts/pst/NewLife.py
Fixes check determining whether PC on level up is TNO or not. The attribute assignment window should be shown for TNO only.
Fixes #657
=> Fix opening attribute window for TNO only

gemrb/core/Scriptable/Actor.h, gemrb/plugins/CREImporter/CREImporter.cpp, gemrb/plugins/GAMImporter/GAMImporter.cpp
Makes save games from GemRB work in PST to the extent we know it did not so far.
See #659
=> PST savegame fix

gemrb/plugins/CREImporter/CREImporter.cpp
See two issues described in #667.
Bit of rationale:
- I stick to the class mask that is calculated by `GetClassMask()` instead of reading it in, as it looks equivalent.
- Looking at this domain spells hack, I think it only makes sense to do so if there are actually spells in the counter. Otherwise, mages get that spellbook tab enabled without anything in it.
=> IWD2: compatibility improvements to save games

gemrb/includes/win32def.h
I am guessing it is ok to remove this completely as GemRB requires a much more recent C++ standard anyway.
=> Remove an old Win32 workaround that conflicts with cmath in MSVC2019

gemrb/core/Interface.cpp, gemrb/core/PluginLoader.cpp, gemrb/core/System/FileStream.cpp, gemrb/core/System/VFS.cpp, gemrb/includes/win32def.h
This makes sure to always talk in UTF-16 to Windows where we need to do. This does not fix things related to #650 but makes sure to rely on at least one thing w.r.t. Windows post 9x.
So many string functions to read the docs for, I hope I did not missing anything too critical ...
=> Windows: use Unicode/UTF-16 API

gemrb/core/GUI/TextSystem/TextContainer.cpp, gemrb/core/GUI/Tooltip.cpp
Fixing GCC errors. I guess not limiting the number of lines is the general case?
```
./gemrb/core/GUI/Tooltip.cpp: In member function 'void GemRB::Tooltip::SetText(const String&)':
./gemrb/core/GUI/Tooltip.cpp:130:52: error: missing initializer for member 'GemRB::Font::StringSizeMetrics::forceBreak' [-Werror=missing-field-initializers]
130 |  Font::StringSizeMetrics metrics = {Size(), 0, true};
|                                                    ^
./gemrb/core/GUI/TextSystem/TextContainer.cpp: In member function 'virtual void GemRB::TextContainer::DrawContents(const GemRB::ContentContainer::Layout&, const GemRB::Point&)':
./gemrb/core/GUI/TextSystem/TextContainer.cpp:712:56: error: missing initializer for member 'GemRB::Font::StringSizeMetrics::forceBreak' …
```
=> subviews: fixing the remaining font-related compiler errors

gemrb/core/PluginLoader.cpp, gemrb/plugins/DirectoryImporter/DirectoryImporter.cpp, gemrb/plugins/GUIScript/GUIScript.cpp
Found three things that may result in crashes or unforeseen behaviour. One is the issue, the others look reasonable to address.
fixes #692
=> [subviews] DirectoryIterator: prevents some unwanted behaviour on filter flags

.gitignore, gemrb/includes/exports.h
This is the pull request I should have started with. I am still trying to do basic housekeeping, but I can't seem to manage to do anything without github desktop tripping over visual studio or vice versa. At least github desktop doesn't create a load of its own junk though. This should cover ignoring all the local stuff that MSVC creates.
I'll split that mingw tweak to another branch for my own sanity. I thought of another scenario which I hadn't thought of before as well, so I need to double check it is ok. Never imagined one line in one file would end up being so annoying...
=> Msvc tweaks: updated gitignore & most common compiler warning silenced

gemrb/GUIScripts/iwd/CharGen.py
This fixes #723. Spells were shifted by one, it was impossible to learn first as well.
=> Fix learning memorizing spells for cleric spellbook in chargen

gemrb/core/Animation.cpp
fixes #732
So when an animation loop overflows, `starttime` was reset to 0. From what I see, `starttime` is used to determine the timestamp of the last update of the frame counter. But when it is set to 0, this code https://github.com/gemrb/gemrb/blob/4831717a78b1e97cf1823138824b7494619143ed/gemrb/core/Animation.cpp#L133-L139
in the next frame request will make it look like "just now". So we have a whole cycle of pos 0 in addition as this line won't do anything then:
https://github.com/gemrb/gemrb/blob/4831717a78b1e97cf1823138824b7494619143ed/gemrb/core/Animation.cpp#L158
=> Animation: prevents first frame of new loop to remain for too long

gemrb/core/CodepageToIconv.h
With GCC v10.1, this one can no longer be omitted here, obviously.
=> GCC 10.1 fix in Windows iconv mapping

gemrb/GemRB.cpp
I was not able to build gemrb.cpp on VS2019 without including 'locale.h'
As per Brad's suggestion, using 'clocale' works fine
Without this, the set_locale function chokes the build as 'undefined'
I don't see any reason why it wouldn't work, but if someone throws me a Polish or German dialog(f).tlk set for any game I can verify it works for me.
=> Include <clocale> to make MSVC happy with PR #650

android/GEMRB_Android.mk, gemrb/core/CMakeLists.txt, gemrb/core/FileCache.cpp, gemrb/core/Makefile.am, gemrb/core/System/MappedFileMemoryStream.cpp, gemrb/core/System/MappedFileMemoryStream.h, gemrb/core/System/MemoryStream.cpp, gemrb/core/System/MemoryStream.h, gemrb/core/System/VFS.cpp, gemrb/core/System/VFS.h, gemrb/plugins/BIFImporter/BIFImporter.cpp
As discussed in #738, now the approach with mmap and its Windows counter part.
Reduces loading time up to 80%, can't even read some of the loading screen texts any more. Please try out!
=> BIFImporter: Memory mapped file reading

CMakeLists.txt, gemrb/CMakeLists.txt, gemrb/vcpkg_deps.cmake
I am suggesting this patch only as temporary fix to the only gripe I have with the almost serendipitious "VCPKG" package manager for Visual Studio. 
To be completely fair, It is actually a really nice package manager that works in general like apt or pacman etc, and works really well up until the point that it.... well.. doesn't
Unfortunately, GemRB seems to be outside of the use cases they may have tested. It makes a grand and well considered effort to place dependency dll files where they should be found, but it unfortunately fails to satisfy GemRB because of the fact that its plugins are in a different directory to the executable file. 
This is a really basic workaround that copies expected dll file names to the target directory so that the game can at least run. 
In the back of my …
=> Substitution for VCPKG's dll placement script

gemrb/GUIScripts/GameCheck.py, gemrb/GUIScripts/bg1/MessageWindow.py, gemrb/GUIScripts/bg1/Start.py
=> BG: disables mission pack button in menu when not installed

gemrb/core/Interface.cpp, gemrb/core/Interface.h
One more complaint from Visual Studio's compiler.
One less thing stopping subviews from building on VS2019.
This is all that was needed to close  #766
=> Moved a GUIFactory.h #include to appease Visual Studio

gemrb/core/CharAnimations.cpp, gemrb/core/Palette.cpp, gemrb/core/ScriptedAnimation.cpp, gemrb/core/WorldMap.cpp, gemrb/plugins/GUIScript/GUIScript.cpp
Related to the discussion in #767 , this allows compilation of some recent palette handling changes that work for gcc/clang but not for 'cl.exe'
This is the last blocking issue for the building this dev branch on Windows 
Tested on Torment and Icewind Dale. I would have tested on BG1/2 as well, but I stupidly forgot that I only have a disc version when I was tidying up files last, and I haven't had a CD/DVD drive for at least 10 years
=> Some tweaks to palette handling for MSVC

gemrb/core/Scriptable/Actor.cpp
Fixes crash from #797
As mentioned in that issue, it seems to just be a symptom of the incomplete PST animation code
=> Actor.cpp: avoid trying to use null 'anims'

gemrb/GUIScripts/iwd/CharGen.py
As @lynxlynxlynx pointed out, druids shouldn't be able to select racial enemy.
=> IWD: Don't open racial enemy selection window in chargen for druids

gemrb/unhardcoded/pst/vcremap.2da
This fixes the annoyance of critical hits/misses playing the rare select 3/4 sounds #824
That side issue can then be closed, while the larger issue is pending.
Indexes 90/91 were simply picked as entries that seem have no existing usages in the cre data, no other particular reason, they could be subject to change as needed
=> PST: Patch for Critical hit/miss annoyance #824

gemrb/GUIScripts/GUICommonWindows.py
BioTable.GetRowName (Specific+1) was returning VHAILOR
Deleting a single character is enough to close #522
Whoops.
=> PST: TNO Avatar Reassignment is using the wrong table row

gemrb/GUIScripts/pst/GUIREC.py
This fixes one small item from #825
When you level up, your total hitpoint limit is increased, but you are shortchanged being given the new HP because they are updated in the wrong order.
Only 60 more to go!
=> pst/guirec: increase maxhp before current hp

gemrb/GUIScripts/pst/GUIINV.py
This is to disable the 'OnDragItem' handler in the first Quick Weapon slot, when it is being used to display the default weapon, eg Nameless' fists, Annah's daggers, Morte's  teeth, etc. Fixes one part of #804 / #841
=> PST/GUIINV: Don't error if one tries to drag the fist weapons

gemrb/GUIScripts/iwd/CharGen.py, gemrb/plugins/GUIScript/GUIScript.cpp
This solves #764. I've added optional boolean parameter to QueryText(), my only concern is whether it should be positional argument, or keyword one. Initially, I wanted to use keyword one, but that requires changing method signature, and I run into issues [here](https://github.com/gemrb/gemrb/blob/5b0cf79e5d388f718585b96586535c1fe5970fb2/gemrb/plugins/GUIScript/GUIScript.cpp#L15801), so I would have add another macro that would cast it to PyCFunction, as it is described [here](https://docs.python.org/2/extending/extending.html#keyword-parameters-for-extension-functions), I suppose. Current `METHOD` macro expects PyCFunction, not PyCFunctionWithKeywords. Do you think positional optional argument is fine, or it should be keyword one, which would require a little more work?
=> Optionally use system encoding in QueryText

gemrb/GUIScripts/GUIOPT.py
max hp on level up can now be enabled in IWD game options (fixes issue 878)
- [*] Commit messages are descriptive and explain the rationale for changes
- [*] I used the same coding style as the surrounding code 
- [*] I have tested the proposed changes
- [*] I extended the documentation, if necessary
- [*] The proposed change builds also on our build bots (check after submission)
=> added game options check for IWD1 in GUIOPT.py

gemrb/core/Map.cpp, gemrb/core/PathFinder.cpp, gemrb/core/Scriptable/Actor.cpp, gemrb/core/Scriptable/Scriptable.cpp, gemrb/core/Scriptable/Scriptable.h
- Makes `IsWalkableTo` only check points directly on the line, leaving the caller the burden of checking for tight spaces. `FindPath` does this (`PathFinder.cpp:321`), `RunAway` calls `FindPath`, my `RandomWalk` never cared about LOS and just leaves the burden to `Movable::DoStep`. 
- Makes `Actor::SetMap` block the searchmap when appropriate. 
- Makes `Movable::WalkTo` check if the path has just been abandoned. Fixes #893.
- Makes `Map::FindPath` not try to path to places that are too small to fit. Fixes #890 .
- Allows for calling `Movable::WalkTo` with `prevTicks == 0`, i.e. if `Ticks` hasn't been updated yet
- Adds check for zero `speed` to `Map::GetBlockedInLine`. Fixes other bug mentioned in #893.
- Makes `Movable::WalkTo` give up at a smaller distance. Fixes #900 .
=> Pathfinder robustness upgrade

gemrb/core/Scriptable/Scriptable.cpp
- Makes `Movable::DoStep` not abandon path when stopping because of a door: actors should try and re-path, if possible.
- Makes `Movable::WalkTo` only be rate-limited while moving, since the purpose of rate-limiting is avoiding actors being stuck on a moving target.
=> Movable: Minor bugfixes

gemrb/core/Inventory.cpp, gemrb/core/Inventory.h, gemrb/core/Map.cpp, gemrb/core/Scriptable/Actor.cpp, gemrb/core/Scriptable/Actor.h, gemrb/plugins/AREImporter/AREImporter.cpp, gemrb/plugins/GUIScript/GUIScript.cpp
I took an initial pass at #901 .
At first glance most of the GUIScript.cpp calls (namely to `Inventory::RemoveItem` and `Inventory::AddSlotItem`) don't recalculate the weight, so there's not much simplification there. I will try to take a look at their other calling points to check if they could do so, unless someone recommends against it.
=> Refactor Actor::CalculateSpeed (WIP)

gemrb/core/GameScript/GameScript.cpp, gemrb/core/GameScript/GameScript.h, gemrb/core/Scriptable/Scriptable.cpp
Fix for #542 .
I added the same logic to both `SetScript` variants, even though I'm not sure the 2-arg variant is currently callable from within a script.
I think this eliminates the need for the `Canary` stuff; I can remove that in another commit or submit a separate PR if desirable.
=> Guard against scripts committing suicide before they're done running

gemrb/plugins/SDLVideo/GLSLProgram.cpp, gemrb/plugins/SDLVideo/SDL20GLVideo.cpp
The GL context initialization in 'GLVideoDriver' requests OpenGL (ES) 2.0 from SDL2,
but SDL2 doesn't guarantee the context returned will have the same version [1].
To avoid any compatibility issues with a superior GLSL version, add the GLSL version to the shader code,
depending on the GL context requested (non-ES vs. ES).
* when expecting an OpenGL 2.0 context, set version to 110
* when expecting an OpenGL ES 2.0 context, set version to 100
[1] - https://wiki.libsdl.org/SDL_GLattr#OpenGL
- Fixes #932.
- Minor: 
* replaced a few error messages (_couldnt .._ replaced with the more ubiquotus _Unable to_)
* added a couple of log messages about the initialized GL context.
====
=> add OpenGL shaders versioning for GLSL compatibility

gemrb/plugins/SDLVideo/SDL20Video.cpp
Fixes compilation with SDL2 < 2.0.10, broken by https://github.com/gemrb/gemrb/pull/936.
=> SDL20Video: ensure SDL_HINT_RENDER_BATCHING is supported at compile time

platforms/windows/window.rc
Now that the platforms directory has been created, this fixes a tiny issue of MSVC not being able to find the program icon while building, as the artwork directory is now two levels above instead of one.
=> Window.rc : the artwork directory is now one more level above relatively

gemrb/unhardcoded/pst/clskills.2da, gemrb/unhardcoded/pst/skills.2da
This is the prerequisite first step of implementing the common skill scripts in PST
The first commit seems to be a simple oversight or typo
The second commit adds the skills.2da table that will be needed later with the correct label strrefs (there is no description text needed/used since the level up screen is much simplified)
I think the skill id's are correct, or at least, they match up with the entries for all the other games. This part I am not 100% sure how they are used or whether they would be any reason for them to be different for PST.
=> PST clskills.2da fixes and skills.2da draft

gemrb/GUIScripts/LUSkillsSelection.py, gemrb/GUIScripts/pst/GUIREC.py
This is not meant to be an actual pull request for this issue, it's just so far all I have been able to come up with. It works, but I hate it.
The common LUSkills script very almost nearly works with PST apart from a few annoying stumbling blocks:
1: The + and - buttons are reversed left to right
2: Instead of the name labels and point fields being separate sequences in the CHU file, they are instead in label, number, label, number order.
3: There is no text description area or associated hint text to display, so that part must be disabled
When I originally got this to work, I dropped it to look at other stuff because I was in gaming/testing mode, but deep down I am still convinced it could be a lot better and cleaner.
It gets frustrating having to add if/else blocks that reference PST by …
=> PST Level up thief skills initial support

gemrb/core/GUI/WindowManager.cpp
A widescreen fix for the subviews branch. This makes the frames work in my 960x600 resolution, and I've tested with 1024x768 as well.
=> Fix loading and display of frames for widescreen resolutions

gemrb/core/GUI/GameControl.cpp, gemrb/plugins/SDLVideo/SDLVideo.cpp
This fixes what seems to be a simple oversight and brings behaviour in line with the IE. When the Tab key is released, the overhead hitpoint display should disappear.
There were two problems, fixed in two separate commits - there was no code to hide the hitpoints in the KeyUp handler, and SDL didn't properly translate its keycodes. The code in SDL could probably be improved further, but I think what I have is the minimum safe fix.
=> Make hitpoint display go away when Tab is released

gemrb/GUIScripts/GUICommonWindows.py, gemrb/GUIScripts/GUIWORLD.py, gemrb/core/GUI/GameControl.cpp, gemrb/plugins/GUIScript/GUIScript.cpp
I noticed a regression from master: the keys '1'..'6' no longer work in the inventory (or on the character screen). The problem is that they are handled in GameControl, but that gets disabled when a top window is added.
Adding hotkeys to the portrait buttons seems to fix it.
Out of curiousity, where exactly are the hotkeys 'I' and 'R' added? No matter how hard I grep I just can't find the location. I'm guessing it's InitOptionButton, but if so, where does it get the keys 'I' and 'R'?
=> Make '1'..'6' hotkeys for the portrait buttons

gemrb/plugins/BAMImporter/BAMFontManager.h, gemrb/plugins/MVEPlayer/MVEPlayer.cpp, gemrb/plugins/SDLVideo/SDL12Video.h, gemrb/plugins/SDLVideo/SDL20Video.h, gemrb/plugins/TTFImporter/TTFFontManager.h
Clang has some warnings: the previous change added missing override
keywords to some functions, but that made two class definitions
inconsistent, and clang warns about this while gcc doesn't.
The other issue only clang warns about is passing PatternHolder to
a variadic function.  Fixed by passing Pattern * in that particular
case only.
=> Fix fallout from previous palette changes

gemrb/core/Map.cpp, gemrb/core/Map.h, gemrb/core/Scriptable/Actor.cpp
There were a number of problems here.  The first one is that directly
after creating a character, BG2 goes into pause mode, which looks like
a lockup to the user, since the GUI isn't shown at that point.  The
issue is that Actor::UpdateActorState doesn't check for visibility
and triggers autopause for the Cambion, which is somewhere else
entirely.  I believe this code isn't needed at all, and deleted it.
The next problem is the check in Map::InitActor.  This has an
isVisible check using actor->Pos, but the position isn't set at that
point, it's 0,0.  Most callers of AddActor appear to follow up with
SetPosition (and you can't swap the two).  I removed the
ActorSpottedByPlayer call in this function, and added a log message
to show an error in case the condition ever triggers, which really …
=> Fix autopause on enemy sighted

gemrb/core/Video.cpp
The fog of war is currently all messed up.  The reason is that we lose the mirroring flags in CreateAlpha.
=> Fix fog of war display

gemrb/core/DialogHandler.cpp
Fix for #539 (endless conversation loop in PST AR0511).
=> Call LeaveDialog() when changing conversation target

gemrb/includes/exports.h, gemrb/vcpkg_deps.cmake
Various tweaks for building with MSVC - these were just some other small things I had to change to get back to normal
1: Renables deployment of dll's to the build directory for quick testing. I think the original purpose of this probably didn't appear clear, so it went away with the cleanup.
2: Disables a new warning related to gamescript.h, hundreds of "c4138: /* found outside of comment" messages. Not sure what suddenly caused them to start appearing.
3: When 'installing' Dll deployment was not happening when RelWithDebInfo option is used. I tend to use this one, it uses the same release library set
4: Prefer copying the system python version if it exists, otherwise use the vcpkg version. I hope this change works fine with appveyor, am I correct in thinking that making a pull request …
=> MSVC build tweaks

gemrb/core/GUI/GameControl.cpp
Currently, it can be difficult to initiate movement or combat, since a
slight movement of the mouse before releasing triggers rectangle select
mode.  I checked with the IE, and it also applies a deadzone so that
you can move the mouse a little between click and release.  This change
implements that.
The deadzone in IE is pretty large, around half of a reticle, so I bumped
ours as well.
One issue remains: IE shows feedback immediately on mouse press, rather
than waiting for mouse release, which makes for a better user experience.
=> Use a deadzone when going into rectangle select mode

gemrb/core/IniSpawn.cpp
There is a small ease of life feature in the original game, when Nameless dies, he stays selected, since you come back to life moments later (well, from TNO's point of view, I guess)
I made this tweak a while ago, after noticing a convenient place here https://github.com/gemrb/gemrb/commit/b7cbeb87df04b55b25585c1c97fec5f0ae799661, but I was wondering if it could potentially cause any problems
It seems to work alright, however, there is a worrying comment in Scriptable.cpp at Selectable::Select https://github.com/gemrb/gemrb/blob/e14fe1ac692a999d6acb0203bf1b632152141a5e/gemrb/core/Scriptable/Scriptable.cpp#L1816-L1817
This is only really a fix for a minor annoyance, but I was hoping to get some feedback so I can scratch it off the list. Can the condition that the comment warns about …
=> RespawnNameless():  Reselect TNO after death

gemrb/core/PathFinder.cpp, gemrb/core/Scriptable/Scriptable.cpp
- Tweaks a check that gives up on pathfinding to use `MAX_OPERATING_DISTANCE` in order to be consistent with the `Actions` code.
- Tweaks a "too big to fit" check in `Map::FindPath` to account for maximum allowed distance. Tested with the Draconis battle that prompted it in the first place.
Prompted by #952
=> Tweak distance checks

gemrb/plugins/SDLAudio/SDLAudio.cpp, gemrb/plugins/SDLAudio/SDLAudio.h
Added simple Mix_Chunk caching for SDLAudio. Pretty much the same as one in OpenAL plugin, but with fixed bug, that allowed removing cached sounds just after adding them.
Judging by the docs, removing the chunks should be done with Mix_FreeChunk, but it resulted in a massive memleak for me, so I've tried doing everything manually.
=> SDLAudio caching

gemrb/core/Holder.h
It was incorrectly calling release, presumably because the only
instances of MakeHolder are with Palette as a template arg, and
before Palette used Holder, it started with a refcount of 1 instead
of the normal 0 for other Holders.
=> Fix MakeHolder to get the reference count right

gemrb/core/CharAnimations.cpp, gemrb/core/CharAnimations.h, gemrb/core/GUI/Button.cpp, gemrb/core/GUI/Label.cpp, gemrb/core/Interface.cpp, gemrb/core/Map.cpp, gemrb/core/Projectile.cpp, gemrb/core/ScriptedAnimation.cpp, gemrb/plugins/BAMImporter/BAMImporter.cpp
As promised in the other PR, here is a followup patch to clean up a bit more after the PaletteHolder changes. These changes are optional, they are not expected to have a user-visible impact.
FreePalette still remains, since the CharAnimations is hard to follow and I wanted to get the simple cases out of the way first. The second patch in this set contains an initial cleanup for CharAnimations to fix name shadowing.
=> FreePalette followup

gemrb/GUIScripts/LUProfsSelection.py
This one seems like an odd issue to remain for so long, but it really looks to me like the +1 is just wrong. Maybe someone wants to double check they are seeing the same problem before merging? Below is the commit message.
When creating a character in BG2, the weapon proficiencies can be scrolled
down beyond the end of the list, with an empty entry at the bottom.
Adding a few Log calls, the first entries of the table are all the
actual proficiencies, ending in Two Weapon Style. Then follow a number of
entries that are recognized as invalid, and ProfCount is reduced for
these.  Finally, there is one entry that is not recognized as invalid,
but calling GetString on it only produces an empty string - and when
scrolling past the end, there is indeed an empty row.
The RowCount calculation has …
=> Correct proficiencies scrollbar

gemrb/core/GameData.h, gemrb/includes/win32def.h, gemrb/plugins/WEDImporter/WEDImporter.cpp
I was just checking to see if I could still build Subviews with visual studio and found some new issues.
1: Apparently, using #define _USE_MATH_DEFINES before cmath is useless under MSVC, people report they can only get it to work if it is set as a command line directive, which is why there have to be M_PI defines in win32def.h
I worked around it by adding it to the core CMakeLists.txt, since it seems that is where the defines are needed, but I don't know if it will cause any issues, I don't really know why it is optional
2: The WEDimporter refused to build because back_inserter was not declared, I found you have to include iterator
3: The window.rc moved, so I cherry picked the commit from master that updates the location of the icon
This gets me as far as  40ce03e , but after that I am …
=> Subviews MSVC build issues

gemrb/GUIScripts/pst/GUIWORLD.py
This is to fix the erroneous enabled appearance of the close button when in normal dialog, should close #445
=> Pst Message Window Close button

gemrb/GUIScripts/GUILOAD.py
This appears to fix the listing of games when there are less than 5 saved
Fixes #1005
=> GUILOAD: Start savegame Topindex at 1 instead of 0

gemrb/GUIScripts/iwd2/Race.py
Without this, character generation shows an empty list when trying to
select race, and produces this python error:
Traceback (most recent call last):
File "./GUIScripts/iwd2/Race.py", line 37, in OnLoad
RaceCount = CommonTables.Races.GetRowCount ()
AttributeError: 'NoneType' object has no attribute 'GetRowCount'
=> Make sure races are loaded in IWD2

gemrb/GUIScripts/InventoryCommon.py
This should hopefully fix the rest of #998
The last inventory PR fixed the ability to enter the dialog mode, but I missed the fact that the inventory window does not close like it should in subviews branch, so it was overall still not functional.
This changes the close function to what I think is the newer method (please correct me if I'm wrong, but it does work in game)
=> InventoryCommon.DialogItemWindow: Update the inventory window closing method

gemrb/GUIScripts/GUICommon.py, gemrb/GUIScripts/LUCommon.py, gemrb/GUIScripts/LUSkillsSelection.py, gemrb/GUIScripts/pst/GUIREC.py, gemrb/GUIScripts/pst/NewLife.py, gemrb/core/Scriptable/Actor.cpp
I recently started rebasing the changes to PST level up I have been working on top of the subviews branch - it gives me a chance to look at everything twice, it avoids having to worry about merge conflicts with master, and also it means I can test for new bugs and regressions in the game along the way (of course not just in the level up code, but anything else I encounter)
I already found and fixed two new problems. One was an unintended consequence of my last skills patch which broke in subviews because the CreateTextArea function seems to be different. Another is that NewLife.py was hiding the various in game windows, but not setting them visible again after level up.
I also included here one small change for discussion, patching the common level up code to work with TNO's separate XP …
=> Pst level up subviews

gemrb/GUIScripts/pst/GUIREC.py
This only applies to original save games, which don't seem to respect the IE_SPECIES stat of player characters
Should close #1025
=> pst/GUIREC: Fix annoyance of missing species display on record sheet

gemrb/GUIScripts/pst/GUIREC.py
This commit was actually meant to be the last part of #1021 and the handling of each different class level for TNO, but got left out before that was merged.
I was just going bundle it with #1023 at first, but since I'll be rethinking the weapon proficiency handling and that part of GUIREC in general, I've split it out from there so that it doesn't end up getting lost.
=> pst/GUIREC: Handle saving of TNO level in the correct Stat

gemrb/GUIScripts/CommonTables.py, gemrb/GUIScripts/GUICommon.py, gemrb/GUIScripts/pst/GUIREC.py, gemrb/unhardcoded/pst/charprof.2da, gemrb/unhardcoded/pst/weapprof.2da
This is a redo of #1023, implementing the individual character proficiencies via a 2da table
Also includes the various changes to adjacent code : fixing the specific checks, shuffling the hp/thaco, slight tidy up of saving throws
If this is all ok, I can easily move on to finish #176 , all that is remaining are spell slots (which trivially works with LUSpellSelection) and the specialisation bonuses for TNO
=> PST Level up Proficiencies w/table & fixes

gemrb/GUIScripts/LevelUp.py
A change from a few months back to clean up the BG2 level up window interferes with the other games, BG for example doesn't have this control, so the UI breaks down on the Level Up screen.
=> LevelUp.py Character Generation label

gemrb/GUIScripts/pst/GUIPR.py
fixes #1057
There was simply nothing saving the window ID as a global so that UpdatePriestWindow could manage it.
=> pst/GUIPR: Store the Window ID as a global

gemrb/core/GameScript/GSUtils.cpp
This is to fix the annoyance in #1053
=> GSUtils: Disable the printing of verbal constants to the console in PST

gemrb/plugins/AREImporter/AREImporter.cpp, gemrb/plugins/WEDImporter/WEDImporter.cpp
Fix for #167 and some further progress on #163 .
Many bits/flags are still totally ignored -- notably A_ANI_BACKGROUND or whatever replaces it.
I saw improvements in most PST animations with these changes, but they could definitely use some more testing.
=> PST-specific animation- and wall-flag changes

gemrb/GUIScripts/GUICommon.py
For #819
Although I've found other issues with dual class worth chasing while testing, this particular fix for DC from kitted classes seems to be ok, I tested with a kensai, berserker, swashbuckler, beastmaster, avenger and cleric of lathander to various different combinations, and levelled each one up with 250000 XP to be sure the correct class was being used.
=> Dualclass kitindex

gemrb/GUIScripts/GUICommonWindows.py
An extra rest button that wasn't in the original game, this adds a nice improvement from bg2/iwd and also works around the issue in #1074
=> BG1: Add a BG2/IWD style rest button to the main sidebar

gemrb/core/Scriptable/Actor.cpp
Prevents running UpdateActionsWindow on repeated MS_NONE modal state updates (while walking to open/close the door or during the spell casting).
=> Avoid running UpdateActionsWindow on repeated MS_NONE modal state updates

gemrb/GUIScripts/InventoryCommon.py
This should fix the item info display for PST's default weapon. (#841) It appears to work for all NPCs. However I am not sure how this is handled in the other games. Do they even have this functionality? Just opening as a draft PR in case it needs amending.
=> PST: Enable item info display for the 'default' weapon

gemrb/core/GUI/EventMgr.cpp, gemrb/core/GUI/TextEdit.cpp
This fixes #679. According to SDL wiki [TextInputEvent](https://wiki.libsdl.org/SDL_TextInputEvent) is always encoded in UTF-8. Converting it to encoding used by game fixes problem. Note that convention is from string with multi byte characters, to one that has single-byte ones (at least in my case), which means not all characters can be represented… Without changing GemRB internals to use UTF-8 or equivalent, not much can be done. Such failures are handled gracefully, i.e. some gibberish is presented like before.
I also trimmed trailing whitespaces in files I edited, and one mistake I found by occasion.
=> Handle inserting non-ASCII characters in text edit

gemrb/core/GUI/WindowManager.cpp
Observed behaviour: Click on the rest button, wait for the movie to start,
then click on the same screen position again.  The game aborts with
Window.cpp:464: bool GemRB::Window::DispatchEvent(const GemRB::Event&): Assertion `target == NULL || target->IsVisible()' failed.
This seems to be caused by leaving trackingWin set after a MouseUp event,
an inconsistency with TouchUp.
Please note that the return value of this DispatchEvent is unused.  While
changing this code, I also removed a return value that looked meaningful
but wasn't, and changed it plain false.
=> Clear trackingWin on mouse up

gemrb/plugins/SDLAudio/SDLAudio.cpp, gemrb/plugins/SDLAudio/SDLAudio.h
Working volume control for SDLAudio plugin. All volume sliders seems to be working now (except ambient, since it's not implemented anyway). Music/Movie volume control is a bit hacky (since `Mix_VolumeMusic` is not supported due to custom music playback function), but functional.
=> SDLAudio volume control

platforms/windows/Win32Console.h
As mentioned in #1161, I cannot build this with MSYS2 WinAPI headers as there is no discrete `consoleapi.h`. The general `windows.h` does the job, and all the exotic color stuff isn't there anymore anyway.
=> Win32Console: fixes building on MSYS2

gemrb/core/Animation.cpp, gemrb/core/GUI/Button.cpp, gemrb/core/GUI/EventMgr.cpp, gemrb/core/GUI/GameControl.cpp, gemrb/core/GUI/TextArea.cpp, gemrb/core/GlobalTimer.cpp, gemrb/core/Interface.cpp, gemrb/core/Scriptable/Actor.cpp, gemrb/core/Scriptable/Scriptable.cpp, gemrb/includes/globals.h, gemrb/plugins/BIKPlayer/BIKPlayer.cpp, gemrb/plugins/MVEPlayer/mve_player.cpp, gemrb/plugins/SDLVideo/SDL20Video.cpp, gemrb/plugins/SDLVideo/SDLVideo.cpp
See #1215
I even found a good example that makes the difference at the same FPS indication:
before:
after:
=> Obtain ticks from an std::chrono implementation

gemrb/GUIScripts/bg2/GUICG4.py
abracerq.2da values for races should always be treated as base for calculation.
abclasrq.2da should be last thing to to consider as it is required boundary.
see #431 
It looks like there still might be an issue with Abclsmod it probably shouldn't impact min values, at least it look like it works that way in originals.
=> GUICG:Fixed faulty stats calculation of min and max values

gemrb/core/Map.cpp
Prevents actors from stopping after setting a new path (they we're stopping in place with walking active animation).
=> Don't stop movement after setting a new path

gemrb/GUIScripts/pst/Clock.py
I've seen Python errors on `Clock` being missing/wrong, resulting in an unusable clock button.
=> PST: Clock setup fixes

gemrb/core/GUI/EventMgr.cpp, gemrb/core/GUI/EventMgr.h, gemrb/core/GUI/WindowManager.cpp, gemrb/core/GUI/WindowManager.h, gemrb/plugins/SDLVideo/SDL20Video.cpp
Some findings:
* `SDL_RENDER_TARGETS_RESET` is exclusively fired for D3D9 (or `direct3d` backend), D3D11 is unaffected at all. Anyway, unlike the removed comment, the [SDL docs imply](https://wiki.libsdl.org/SDL_EventType) that existing textures can be reused. So I think it's the easiest way just to make every window redraw on the next occasion.
* `SDL_RENDER_DEVICE_RESET` is exlusively fired for D3D11 and is not so much related to the issue. From what I read in [MSDN](https://docs.microsoft.com/en-us/windows/uwp/gaming/handling-device-lost-scenarios), it covers some very, very edgy cases that I'd like to ignore here.
See #1317
=> D3D: Scaling on window resizing

gemrb/core/ArchiveImporter.h, gemrb/core/CMakeLists.txt, gemrb/core/Game.cpp, gemrb/core/Interface.cpp, gemrb/core/Interface.h, gemrb/core/SaveGameAREExtractor.cpp, gemrb/core/SaveGameAREExtractor.h, gemrb/core/SaveGameIterator.cpp, gemrb/plugins/SAVImporter/SAVImporter.cpp, gemrb/plugins/SAVImporter/SAVImporter.h
I noticed that save games of later stages in the game take notably longer: Every ARE is extracted into the cache onto the disk. Yet, we don't need all these ARE files right now, and given the progress, some of them never again.
BG1 spills around 260 ARE files into the cache folder, other games a little less for me.
Why not extract only when we really need it? On my very fast NVMe this _only_ saves half a second (and a lot of console entries), but surely some more on HDDs or RPIs -- unfortunately no test hardware at hand right now.
Feel free to discuss first, but I considered this an avoidable practice.
=> Improving load & save time of heavy save games

gemrb/core/GUI/GameControl.cpp, gemrb/core/Map.cpp, gemrb/core/Map.h, gemrb/core/PathFinder.cpp, gemrb/core/Projectile.cpp, gemrb/plugins/AREImporter/AREImporter.cpp
into a single 32bit sprite. This will give great cache locality for everything we need to lookup in a given frame.
if we want we could add a way to dump it to a file for even better debugging
add enhanced DebugOverlay capable of displaying all maps
=> Map: pack lightmap/heightmap/materialmap/searchmap

.appveyor.yml, .github/workflows/builder.yml, .github/workflows/coverity.yml, CMakeLists.txt, gemrb/vcpkg_deps.cmake
Seeing if it builds.
~@bradallred we don't _brew_ anything for python2 on macs - is v3 also available by default?~ Looks like it.
#1425 is a blocker.
=> Py3 defaults

gemrb/GUIScripts/pst/NewLife.py
… would not start at max hp when con >14
Added hpinit.2da support to NewLife.py (issue #935). Fixed issue where the player would not start at max hp when con >14.
=> Added hpinit.2da support

gemrb/core/Scriptable/Actor.cpp
This should fix issue #1462 where portraits were not automatically refreshing when a character leveled up.
=> Fixes issue where portrait would not refresh on level up.

gemrb/GUIScripts/bg2/GUIJRNL.py
Enabled sorting of the Journal.
Added correct messages on button press.
Allow sorting in the Journal.
Related issue: #1367 BG2: Allow sorting of journal entries
=>  BG2: Allow sorting of journal entries #1367

gemrb/core/GameScript/GSUtils.cpp
This will fix the option of enabling and disabling subtitles on the chat log. Issue #1420
=> Change if subtitles option is disable will not show the pc text on the chat log

gemrb/core/System/CString.h
The only thing that prevents #1523 from building for me.
=> Missing CString header for MSYS2/GCC

gemrb/core/Logging/Logging.h
Having `GEM_EXPORT` with the now-template definitions misdefines some linking expectations, resulting in:
```
D:/Sources/gemrb/gemrb/core/Logging/Logging.h:45:17: error: function 'void GemRB::error(const char*, const char*, ARGS&& ...)' definition is marked dllimport
45 | GEM_EXPORT void error(const char* owner, const char* format, ARGS&&... args)
|                 ^~~~~
D:/Sources/gemrb/gemrb/core/Logging/Logging.h:54:17: error: function 'void GemRB::Log(GemRB::log_level, const char*, const char*, ARGS&& ...)' definition is marked dllimport
54 | GEM_EXPORT void Log(log_level level, const char* owner, const char* message, ARGS&&... args)
|                 ^~~
```
=> Fixing the logging header for Windows

gemrb/plugins/SDLVideo/GLSLProgram.cpp, gemrb/plugins/SDLVideo/GLSLProgram.h
I found some oddly bad looking, and unnecessary slow code that's on the hot path when repopulating GLSL uniform variables.
=> Faster GLSL uniforms lookup

gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp, gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.h
The default copy ctor is bad for us.
See #1536
=> SDL sprite copy fix

.appveyor.yml
It's clear from the log the install phase does a rebuild, taking another 9 minutes, instead of just copying the files.
EDIT: eh, it looks like SF doesn't like our ssh set up any more either.
=> appveyor: try not building the whole thing twice

gemrb/core/Map.cpp
Happens only on `-O2` and above for me, not sure what unopt stuff ends up doing here instead:
```
74      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff717fe68 in __vfprintf_internal (s=s@entry=0x7fffffffce70, format=format@entry=0x5555558d49f8 %s_visited, ap=ap@entry=0x7fffffffcff0, mode_flags=mode_flags@entry=2) at vfprintf-internal.c:1647
#2  0x00007ffff719141a in __vsnprintf_internal (string=string@entry=0x7fffffffd100 , maxlen=<optimized out>, maxlen@entry=33, format=format@entry=0x5555558d49f8 %s_visited, args=args@entry=0x7fffffffcff0, mode_flags=mode_flags@entry=2) at vsnprintf.c:114
#3  0x00007ffff723c7a2 in ___vsnprintf_chk (s=s@entry=0x7fffffffd100 , …
```
=> Map: fix for crash in MarkVisited

gemrb/GemRB.cpp, platforms/android/GemRB.cpp
using setenv instead of `#ifdef`
=> restore MALLOC_TRIM_THRESHOLD functionality

gemrb/core/PathFinder.cpp
When switching to Point in 0e0568c the wrong variable was passed
to Clamp.
=> Fix #1599 - Regression in Map::getLine

demo/data/gemrb.ini, gemrb/core/Interface.cpp, gemrb/core/Scriptable/Actor.cpp, gemrb/docs/en/gemrb_ini.txt, gemrb/includes/globals.h, gemrb/unhardcoded/bg1/gemrb.ini, gemrb/unhardcoded/bg2/gemrb.ini, gemrb/unhardcoded/iwd/gemrb.ini, gemrb/unhardcoded/iwd2/gemrb.ini, gemrb/unhardcoded/pst/gemrb.ini
Controls whether damaging innocents affects the player reputation.
Off for BG1 only.
Fixes #1603
=> Add DAMAGE_INNOCENT_REP flag

gemrb/core/Strings/CString.h
I was looking at the problem below (happens on some enemy encounters in IWD2), and that assertion made no sense in what it was supposed to do: prevent overrunning the original string's memory.
That `static_cast` prevents a warning, as GCC otherwise complains about comparing different signs which I do not understand by looking at all the unsigned the types, so ...
```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737316622912) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737316622912) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737316622912, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff70ae476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff70947f3 in …
```
=> CString: Substring assertion fix

gemrb/core/Interface.cpp, gemrb/core/Interface.h, gemrb/core/TableMgr.h, gemrb/plugins/2DAImporter/2DAImporter.cpp
See #1616, there were two errors and I noticed a bunch of stuff around it that could be type-wired and cleaned with `uint32_t` at the end.
=> Replace some uses of size_t

gemrb/core/Core.cpp, gemrb/core/DialogHandler.cpp, gemrb/core/EffectQueue.cpp, gemrb/core/Spell.cpp, gemrb/plugins/FXOpcodes/FXOpcodes.cpp
Calling a non-static member function on a null pointer is undefined
behavior. Added non-null checks at affected call sites.
There are multiple places in the code where Scriptable::As is called on a pointer that can be null. This can cause crashes on some platforms, which I have experienced (I can add a separate bug report with details if it's necessary).
From this discussion (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99074) it seems that versions of GCC from 8 up to 11 are affected.
=> Fix calls to Scriptable::As through null pointers.

gemrb/core/ScriptEngine.h, gemrb/core/System/VFS.h
Two things addressed:
* The initial problem of #1636 
* Errors for unused variables on uses of `ResolveFilePath` on Windows & GCC.
=> Fixes for Windows

gemrb/core/GUI/GameControl.cpp
Would otherwise crash on debug build, at least when running IWD2.
Was doing reserve instead of resize.
=> Formations ctor crash 

gemrb/plugins/BIFImporter/BIFImporter.cpp
There is a mismatching `delete`-operator in use. Interestingly, GCC started to complain about this only today.
=> BIFImporter: wrong delete operator

gemrb/GUIScripts/GUIMG.py, gemrb/GUIScripts/GUIOPT.py, gemrb/GUIScripts/GUIPR.py, gemrb/GUIScripts/bg2/GUIINV.py, gemrb/GUIScripts/bg2/GUIJRNL.py
Added pause when opening:
- Options
- Inventory
- Character Record
- Priest Spells
- Mage Spells
- Sorcerer Spells
- Journal
This is only applying to BG2. Missing what the others do.
Fixing bug #1678
=> Pausing on accessing the menu

gemrb/GUIScripts/Spellbook.py
Normally it would be fine, but an inexplicable bug occasionally converted memorized spell resrefs to lowercase, at which point they would be misparsed and would dissappear from the action bar.
Also, fix an unrelated typo (string + int addition attempt).
This is related to #1709.
=> Spellbook: compare resrefs case-insensitively

gemrb/plugins/SDLVideo/Shaders/BlitRGBA.glsl
Probably a leftover of the very last shader code merge, other color branch was correct already. Looks good now:
Fixes #1712.
=> SDL: fixes alpha channel in shader for grey mode

gemrb/core/EffectQueue.cpp, gemrb/core/EffectQueue.h
Hello again!  Here are some fixes for the spell protection effects, which didn't work properly for quite a while now.  I'll elaborate on the six commit points:
1. "Magic attack" spells such as Pierce Magic now correctly ignore most spell protections they're supposed to remove.  (`check_type()`, `bool pierce`)
Spells with the secondary type 4, which include spell protection strippers (and also Breach), ignore some protective effects, although not all.  [Here's a handy chart.](https://docs.google.com/spreadsheets/d/1y7r2Z3FfZk74NdAVHuZuiNmWh14y1tAytNrsFMSY7zc)  As you can see, they go through decrementing level immunity (Spell Turning), school immunity (Spell Immunity), decrementing level bounce (Spell Turning), and spell trap, although not generic level immunity (Spell Thrust (technically …
=> A number of spell immunity fixes

gemrb/core/GameScript/GameScript.h, gemrb/plugins/FXOpcodes/FXOpcodes.cpp
The old code for `Spell:Cast` effect (which scrolls use) created a `ForceSpell()` action with the target's script name (unless casting on self), but the protagonist has the script name "none" (there was even a comment about that!), so usually the spell would be cast on some other actor with the same name instead.  Really, this extends to any creature with a non-unique script name.
Anyway, now the code uses `GenerateActionDirect()` instead, which takes an actor and directly substitutes its actor ID, and this solves the problem.
=> BG2: fix scrolls cast on other actors instead of protagonist

gemrb/GUIScripts/GUILOAD.py
See #1715. This way the menu music is playing while seeing the load screen, but hands over to the map playlist, or none.
=> GUILOAD: soft-killing the playlist after load screen

gemrb/core/Inventory.cpp
Gold was unfortunately deleted _before_ it could be dropped.  A simple typo, it's only not 0 gold because of `SanitizeItem()`.
=> Fix actors dropping 1 gold on death instead of their IE_GOLD

gemrb/core/Calendar.cpp, gemrb/plugins/ACMReader/unpacker.cpp
There are two problems when trying to compile GemRB on Clang v15 here:
* An effectively unsued variable `month` in `Calendar.cpp`
* Non-UTF8 russian comments in `ACMReader`
I think we can safely drop both these.
=> Clang v15 fixes

gemrb/core/Inventory.cpp
This is a bit controversial, but in the original game the few self-firing ranged weapons with launcher bits set (e.g. Gesen shortbow) could do both with or without ammo.  Some view this as bug, but see for instance [this Beamdog thread](https://forums.beamdog.com/discussion/28124/7413-core-feature-request-the-gesen-bow) where they ultimately decided that it doesn't need fixing.  Personally I'd like this feature, so I submit this PR.
Also, this commit incidentally fixes said weapons so that their thac0 and damage bonuses wouldn't double when firing without ammo (they were counted both as launchers and ammo).
=> BG2: Allow ammo for self-firing launchers and fix their bonuses

gemrb/core/Scriptable/Actor.cpp
A simple typo, the code was supposed to block repetitive messages from similar effects, but due to using && instead of ||, it often ended up blocking many subsequent unrelated saving throw reports.
So basically a boolean logic derp.  Without the fix, I would only see ST messages once every few minutes if at all.
=> Actor: fix displaying consecutive saving throws

gemrb/core/Projectile.cpp, gemrb/core/Projectile.h, gemrb/core/Streams/DataStream.cpp, gemrb/core/Streams/DataStream.h, gemrb/plugins/AREImporter/AREImporter.cpp, gemrb/plugins/BAMImporter/BAMImporter.cpp, gemrb/plugins/BMPWriter/BMPWriter.cpp, gemrb/plugins/CREImporter/CREImporter.cpp, gemrb/plugins/GAMImporter/GAMImporter.cpp, gemrb/plugins/MOSImporter/MOSImporter.cpp, gemrb/plugins/PROImporter/PROImporter.cpp, gemrb/plugins/STOImporter/STOImporter.cpp, gemrb/plugins/WEDImporter/WEDImporter.cpp, gemrb/plugins/WEDImporter/WEDImporter.h
Some minor enhancements to DataStream for reading data along with cleanup in the importers to favor things like ReadRegion/ReadSize/ReadPoint and removal of needless temporaries
I've tested loading+saving+loading in BG2. Will do some more testing in other games soon.
=> Data stream cleanup

gemrb/GUIScripts/LUCommon.py, gemrb/core/Scriptable/Actor.cpp, gemrb/core/Scriptable/Actor.h
> In the original BG1&2, temporary increases in constitution also increased current HP equal to max HP bonus.  In EE, these bonuses also cause equal amount of damage on expiring.  This commit implements the EE behavior, projecting any max HP change from constitution to current HP.
ATM GemRB does not adjust current HP at all, which makes e.g. DUHM significantly worse defensively.
Personally I feel the EE way is more fair (especially if you want to add early Con equipment), that said, the original game behavior is literally one comparison operator change away, if you'd like that more.  Or it could be controlled by those EE flags whenever you implement them.
=> BG: modify current HP following Con changes

CMakeLists.txt, gemrb/core/Map.h, gemrb/core/PathFinder.cpp
I was investigating why there is an extreme slowdown in some cases of changing areas that do not look particularly difficult at a first glance.
Anway, the profilers indicate another interesting thing: When spending a lot of time waiting for map changes, `Map::NormalizeDeltas` has an insane amount of calls, and `sqrt` even consumes some systime.
Looking at this, there one obvious thing: One can do that with only one instead of two `sqrt` operations. And doing a bit of micro-benchmarking fun, it turns out that using something called [Quake Inverse Fast Sqrt](https://en.wikipedia.org/wiki/Fast_inverse_square_root) is even faster, if you can live with tiny little errors that don't really matter here (doing `ceil` and such). What was even mind-blowing: This optimization is not just faster by …
=> Faster vector normalization in Map code

gemrb/plugins/PVRZImporter/PVRZImporter.cpp
Bad C&Ping the memory accessor from the other format, so this was this nicely distorted noise effect. Now we are good:
- [] The proposed change builds also on our build bots (check after submission)
=> TIS DXT1 fix

gemrb/GemRB.cfg.noinstall.sample, gemrb/GemRB.cfg.sample.in, gemrb/core/CMakeLists.txt, gemrb/core/FogRenderer.cpp, gemrb/core/FogRenderer.h, gemrb/core/GUI/GameControl.cpp, gemrb/core/Interface.cpp, gemrb/core/Interface.h, gemrb/core/Map.cpp, gemrb/core/Map.h, gemrb/core/Video/Video.h, gemrb/plugins/SDLVideo/SDL20Video.cpp, gemrb/plugins/SDLVideo/SDL20Video.h
See #1760. Turns out interpolating some vertex colors alone isn't sufficient, we will need to paint cells in a way to cover the edges to look good. Here we are now:
With modern SDLv2 (notice the machine in the lower left, and the room in the upper right):
Fallback:
=> Smooth fog edges

gemrb.6.in, gemrb/GemRB.cfg.noinstall.sample, gemrb/GemRB.cfg.sample.in, gemrb/core/Interface.cpp, gemrb/core/Interface.h, gemrb/core/Video/Video.cpp, gemrb/core/Video/Video.h, gemrb/includes/globals.h, gemrb/plugins/SDLVideo/SDL12Video.cpp, gemrb/plugins/SDLVideo/SDL12Video.h, gemrb/plugins/SDLVideo/SDL20Video.cpp, gemrb/plugins/SDLVideo/SDL20Video.h, gemrb/plugins/SDLVideo/SDLVideo.cpp, gemrb/plugins/SDLVideo/SDLVideo.h
I wanted to give it a try and like to invite you for testing. Since it was suspiciously easy for now:
* `CapFPS` is a new tech setting that allows the user to switch between VSync (on SDL2), some custom frame rate limit and no limit.
* I did a simple approach for handling game state and drawing: Assuming refresh rates are much more frequent than game updates. So don't touch the game state for a while and just draw in the meantime.
* Half the value of `Maximum Frame Rate` is now `ai_update_time`, and that's the frequency of the game state's update.
* There is some annoying workaround for SDL1 to work like it did so far, since it appears to lack VSync handling.
* Some logic to prevent scrolling around the map linearly to the fps, thus becoming too fast and while preventing the current …
=> VSync, FPS capping, Game state update

gemrb/GUIScripts/GUIOPT.py
Fix tooltip delay setting not working #1797.
=> use integer division for TOOLTIP_DELAY_FACTOR

gemrb/GUIScripts/GUIOPT.py
Set delay tooltip to a very high value on max setting ("disable" it).
Ref #1797
=> (effectively) disable tooltips on max delay setting, like description says

gemrb/plugins/FXOpcodes/FXOpcodes.cpp
Fix invisibility opacity limits and pulse interval (#1810)
Original
https://github.com/gemrb/gemrb/assets/1279852/1eddec3e-87d8-4b23-b595-f2f171ae0061
New GemRB
https://github.com/gemrb/gemrb/assets/1279852/5a2f4f1e-477f-4fd4-b42f-94a27c6fc7b3
I'm struggling to match original exactly, because of [brightness/contrast differences](#1098), as well as avatar/color differences.
However, it's closer than current master.
=> set lower limit for invisibility opacity, decrease pulse interval

CMakeLists.txt
Just a QoL thing for people using ccmake or IDEs such as VScode's cmake extension. Options show up on the list of cache variables to be turned on and off.
Still defaults to disabled, so behavior is unchanged
=> Formalize DISABLE_WERROR as a CMake option

gemrb/GUIScripts/GUISTORE.py
See #1873.
`Button` in the first iteration is still the identify button from a few lines above, and that `GUISTMSC` refers to an item box sprite.
=> IWD2 identify store button fix

gemrb/plugins/SDLVideo/SDL20Video.cpp
Project fails to build with SDL Video for versions between  >2.0.18 and <2.0.22.
When trying to build with SDL 2.0.18 I get the following error:
```
lcc: "gemrb/gemrb/plugins/SDLVideo/SDL20Video.cpp", line 597: error #167:
argument of type "const SDL_Color *" is incompatible with parameter
of type "const int *"
reinterpret_cast<const SDL_Color*>(colors.data()),
^
``` 
This happens because prior to libsdl-org/SDL@b7885abc449250fc733a756239d670394d01fe62 `SDL_RenderGeometryRaw()` passes colors as `int*` instead of `SDL_Color*`.
We could simply change the check in `SDL20VideoDriver::DrawRawGeometry()` from 
`#if SDL_VERSION_ATLEAST(2, 0, 18)`
to
`#if SDL_VERSION_ATLEAST(2, 0, 22)`
or check the specific way we pass color based on SDL Video version.
Big thanks to @a1batross for figuring this …
=> Fix build for certain SDL Video versions

gemrb/core/IniSpawn.cpp
Empty critter script name can remove worked cre script name. 
As a result, PST script 1500CS1.bsc step MoveToObject("Hargrim") does not work because it doesn’t find a character with this script name.
=> Fix creature spawn script name

cmake/Helpers.cmake
1. Report the SDL version and handle the `SDL_FOUND` only happen in the default path.
2. When using `-DSDL_BACKEND=SDL2`, cmake goes to the findSDL2 path and it does not set `SDL_FOUND` but `SDL2_FOUND`, so we need to handle that.
=> Report and set SDL_FOUND when -DSDL_BACKEND specified

gemrb/core/Interface.cpp, gemrb/plugins/SDLVideo/SDL20Video.cpp, gemrb/plugins/SDLVideo/SDL20Video.h, gemrb/plugins/SDLVideo/Shaders/BlitRGBA.glsl
Added brightness and contrast to the existing shader #1098.
Actually, there's some confusion about the settings, they called it contrast in the interface and gamma in the configs. But from my testing, it seems that it is also brightness. Just the first one is additive, the other one is multiplicative. (Maybe a better name for 2nd one would be saturation, my color theory is very weak.)
I tried actual contrast formula, as well as actual gamma correction formula, and the results are different, but I can't say that they are better.
There are other options for brightness too, sigmoid and stuff. Maybe worth exploring.
Also fixes brightness not applying on start.
=> Brightness and contrast

gemrb/core/GUI/Button.cpp
Fix shifting menu buttons #1991.
Supercedes #1998.
=> Fix shifting menu buttons

gemrb/GUIScripts/bg2/StartOpt.py
Fix SoA logo flipping to ToB on Options screen, ref #2003.
By the power of ctrl-c/ctrl-v:
=> Fix SoA logo flipping to ToB on Options screen, ref #2003.

gemrb/GUIScripts/GUIOPT.py, gemrb/core/GUI/WindowManager.cpp
GUIopt.py increase only applies if you played around in Options windows.
With cold start, delay setting would pass directly to WindowManager and never get the multiplier.
This moves the final multiplier into WindowManager so it would apply on game start as well.
=> Fix tooltips max setting on game restart, ref #2010.

gemrb/GUIScripts/bg2/Start2.py
Conservatively disabled MultiPlayer button, #2017.
=> Disable MultiPlayer button in BG2, cleanup related GUI code. Ref #2017.

gemrb/core/GameScript/Actions.cpp, gemrb/core/GameScript/GSUtils.cpp
In accordance to similar actions, DisplayString should also emit the DS_CONSOLE flag when not called by an ACTOR.
DisplayStringCore then should not cancel the DS_CONSOLE flag again when not called by an ACTOR.
=> Fix missing intro text, ref #2009

demo/override/gemrb.ini, gemrb/core/Interface.cpp, gemrb/core/Scriptable/Scriptable.cpp, gemrb/docs/en/gemrb_ini.txt, gemrb/includes/globals.h, gemrb/tests/minimal/data/gemrb.ini, gemrb/unhardcoded/bg1/gemrb.ini, gemrb/unhardcoded/bg2/gemrb.ini, gemrb/unhardcoded/bg2ee/gemrb.ini, gemrb/unhardcoded/how/gemrb.ini, gemrb/unhardcoded/iwd/gemrb.ini, gemrb/unhardcoded/iwd2/gemrb.ini, gemrb/unhardcoded/pst/gemrb.ini
Add the 'HighlightOutlineOnly'-flag, which toggles whether the game highlights only the outline of doors and containers (like in BG1), or highlights the complete surface of the object (all except BG1). In accordance with the original games, this flag is enabled for BG1 and disabled for the other games by default.
HighlightOutlineOnly=0
HighlightOutlineOnly=1
=> Add flag to only highlight outline of doors and containers, ref #2011

gemrb/core/System/FileFilters.h
Replace stricmp with strnicmp in order to compare only as much characters as the predicate string has. Otherwise the predicate may be never fulfilled.
=> Fix predicate EndsWithFilter, ref #2007

gemrb/plugins/TLKImporter/TLKImporter.cpp
Do not process invalid seek results. These are garbage anyway and can slow down the subsequent processing considerably.
This affects mostly mods, e.g. Baldurdash's GameTextUpdate for BG1.
#2005
=> Make TLKImporter more resilient, ref. #2005

gemrb/GUIScripts/GUIOPT.py
Add setting the dictionary value back to its previous value, otherwise the internal state of the radiobutton is set wrongly to the last processed button. Also generalize it for all radiobuttons.
=> Fix radiobutton preselection, ref. #1988

gemrb.6.in, gemrb/GemRB.cfg.noinstall.sample, gemrb/GemRB.cfg.sample.in, gemrb/core/GUI/WindowManager.cpp, gemrb/core/Video/Video.cpp, platforms/apple/CocoaWrapper/mac/nibs/GemRB.xib, platforms/apple/defaults.plist, platforms/apple/ios/GemRB.cfg.newinstall, platforms/vita/README.Vita.md
Remove old Fullscreen option from GemRB.cfg, update docs. Ref #1989.
Other video options are still read from cfg, though. Can be confusing too. Not sure why they were duplicated in the first place.
=> Remove old Fullscreen option from GemRB.cfg, update docs. Ref #1989.

gemrb/GUIScripts/bg1/Start.py
Add IE_GUI_BUTTON_NO_TEXT to the MoviesButton in the single player menu when playing without TotSc expansion, otherwise the menu would show a disabled and borderless button with text "Movies".
Apply it also to the ExitButton in the multi player menu in order to avoid using SetText("").
Also reset the Movies- and ExitButton flags to IE_GUI_BUTTON_NORMAL in BackToMain, otherwise these buttons loose their soundeffect when clicking on them. The ExitButton actually already lost its soundeffect before when going into the multi player menu.
=> BG1: fix main menu buttons, #2005

gemrb/GUIScripts/TextScreen.py
Use HardEndPL in order to stop the currently playing music when entering the chapter introductions. This allows the actual chapter music to play.
This doesn't fix the underlying issues with music not playing or stopping properly (e.g. #2008), it merely covers up the symptoms in this special case. But I think that using HardEndPL in this case is actual the right thing to do regardless, especially when it's called already if `MusicName == "*"` (e.g. demo) and the experience with the original games is the same.
=> Fix textscreen not playing chapter music

gemrb/GUIScripts/BGCommon.py, gemrb/GUIScripts/bg1/CharGenGui.py, gemrb/GUIScripts/bg2/CharGenEnd.py, gemrb/GUIScripts/bg2/GUICG3.py
Put calculation of reputation before running the game when importing a character. Otherwise imported characters without a preset reputation (i.e. the predefined character templates cleric, fighter, mage, etc.) have reputation 0.
=> BG1/BG2: fix reputation when importing predefined character templates

gemrb/core/GlobalTimer.cpp, gemrb/core/Map.cpp, gemrb/core/Map.h, gemrb/core/Projectile.cpp, gemrb/core/Projectile.h
See #2037. It's rewritten to the extent that _most_ of the state transition are now left in `::Update()`, with some expiry requests left.
Feel free to test, I checked arrows and a bunch of spells.
=> Projectiles: decoupling state from drawing

gemrb/GUIScripts/GUICG13.py, gemrb/GUIScripts/LUSpellSelection.py, gemrb/GUIScripts/bg1/GUICG1.py, gemrb/GUIScripts/bg1/GUICG10.py, gemrb/GUIScripts/bg1/GUICG12.py, gemrb/GUIScripts/bg1/GUICG15.py, gemrb/GUIScripts/bg1/GUICG19.py, gemrb/GUIScripts/bg1/GUICG2.py, gemrb/GUIScripts/bg1/GUICG22.py, gemrb/GUIScripts/bg1/GUICG3.py, gemrb/GUIScripts/bg1/GUICG4.py, gemrb/GUIScripts/bg1/GUICG5.py, gemrb/GUIScripts/bg1/GUICG6.py, gemrb/GUIScripts/bg1/GUICG8.py, gemrb/GUIScripts/bg1/GUICG9.py, gemrb/GUIScripts/bg1/ImportFile.py
Need to call ShowModal with MODAL_SHADOW_GRAY instead of MODAL_SHADOW_NONE.
It is correct for BG1, but this changes `gemrb/GUIScripts/GUICG13.py` and `gemrb/GUIScripts/LUSpellSelection.py` too. If this is troublesome for the other games then I would need to add game checks.
=> BG1: add missing shadows for modal windows in character creation

gemrb.6.in, gemrb/GemRB.cfg.noinstall.sample, gemrb/GemRB.cfg.sample.in, gemrb/core/InterfaceConfig.cpp, gemrb/core/InterfaceConfig.h, gemrb/plugins/SDLVideo/SDL20Video.cpp
Add an option to specify the SDL_HINT_RENDER_SCALE_QUALITY in GemRB.cfg. The value 'best' is the default.
=> Add ScaleQuality option, ref #1973

gemrb/GUIScripts/PaperDoll.py
- fix uninitialized color stats when OpenPaperDollWindow is called in GUICG13 (SelectColorForPC loaded stats unconditionally from ColorStatsFromPC which are uninitialized at this stage)
- restore PickedColor after Button.SetVarAssoc overrides it
- use lookup by name for colors in ColorStatsFromPortrait
~~remove trailing whitespaces left in the file~~
~~document minimum requirement python 3.10~~
~~The python 3.10 requirement comes from using `Py_IsNone` in gemrb/plugins/GUIScript/GUIScript.cpp.~~
=> Fix minor PaperDoll.py bugs

gemrb/GemRB.cpp, gemrb/plugins/SDLAudio/SDLAudio.cpp, gemrb/plugins/SDLVideo/SDL12Video.cpp, gemrb/plugins/SDLVideo/SDL20Video.cpp, gemrb/plugins/SDLVideo/SDLVideo.cpp, platforms/android/GemRB.cpp, platforms/vita/GemRB.cpp, platforms/windows/GemRB.cpp
Ensure destruction of OpenGL and SDL resources before quitting SDL and use
SDL_QuitSubSystem instead of SDL_Quit in case unloading a shared library
still depends on SDL. The subsystems audio, joystick and gamecontroller
are quitted explicitely now.
Ref. #2004
=> Fix segfault on shutdown

gemrb/core/Game.h, gemrb/core/Map.cpp
Fallback to the songlist from masterarea in order to play the correct battle music.
=> BG1: fix wrong battle music in subareas without songlist

gemrb/core/Bitmap.h, gemrb/core/Core.cpp, gemrb/core/GUI/EventMgr.cpp, gemrb/core/GUI/GameControl.cpp, gemrb/core/GUI/GameControl.h, gemrb/core/GUI/TextSystem/Font.cpp, gemrb/core/GameScript/Actions.cpp, gemrb/core/GameScript/GSUtils.cpp, gemrb/core/GameScript/GSUtils.h, gemrb/core/GameScript/Triggers.cpp, gemrb/core/Geometry.cpp, gemrb/core/Geometry.h, gemrb/core/Map.cpp, gemrb/core/Map.h, gemrb/core/Orientation.h, gemrb/core/Palette.cpp, gemrb/core/Particles.cpp, gemrb/core/PathFinder.cpp, gemrb/core/PathFinder.h, gemrb/core/Projectile.cpp, gemrb/core/RNG.h, gemrb/core/Region.cpp, gemrb/core/Scriptable/Actor.cpp, gemrb/core/Scriptable/CombatInfo.cpp, gemrb/core/Scriptable/Scriptable.cpp, gemrb/core/Scriptable/Scriptable.h, gemrb/includes/globals.h, gemrb/plugins/BIKPlayer/BIKPlayer.cpp, gemrb/plugins/BIKPlayer/rdft.cpp, gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h
we should be using `float_t` for math operations since we don't care about scientific precision. This allows the compiler to select the native floating point type for the architecture.
additionally, we should always use `std` for invoking math functions to use an appropriate overload that can be reduced to a compiler builtin suitable for the native arch. non `std` math functions are the `C` functions with only one signature and probably cant always get inlined.
=> optimize some of our math

gemrb/core/GUI/View.cpp
I noticed that opening some text sections, like a mildly filled journal or dialogs, drops FPS by up to 75%. 
That is because 382ed935c7c4d54a882b21abd9431744db767511 checks whether invisibility is set to get a background redraw of something after turning invisible. Problem: scrollbars may be invisible by design, so that neighbouring content view is marked dirty and thus it draws fonts over and over again, even if nothing actually requires redrawing.
I made `ScrollBar` exempt from counting for this invisibility check, not sure if the name suits well but I still can't come up with any better one.
=> Fix against severe FPS drops by scrollbar 

gemrb/core/Interface.cpp, gemrb/core/SaveGameIterator.cpp, gemrb/core/System/VFS.cpp, gemrb/core/System/VFS.h, gemrb/plugins/GUIScript/GUIScript.cpp, gemrb/tests/core/System/Test_VFS.cpp
Some issues fixed I encountered earlier today:
1. Crash when saving with non-ASCII characters since code path used open setting `SystemEncoding` when everything else is expected UTF-8 regarding paths for now, so invalid bytes.
1. Underlying VFS fixes on Windows after that was fixed.
1. Cannot delete directories on Windows with non-ASCII chars from FS.
=> Fixes around save game directories

gemrb/plugins/WEDImporter/WEDImporter.cpp
Similar to #1790, #2104, Clang on Raspberry Pi will warn that `-frounding-math` is not supported on this platform, and the same crash will happen again.
So instead of this annoying flag handling, let's get rid of this `ceilf` here.
=> WEDImporter: getting rid of float math

CMakeLists.txt, cmake/cmake_config.h.in, gemrb.6.in, gemrb/core/Interface.cpp, gemrb/core/InterfaceConfig.cpp, gemrb/core/InterfaceConfig.h, gemrb/plugins/SDLVideo/SDL20Video.cpp
It appears that the original intent of this macro was never validated, and I've noticed that choosing _Full screen_ at the in-game options makes no difference to this code path. Can be tested by starting GemRB from TTY on a Wayland computer with something like a full HD screen.
=> CMakeLists: removes `SDL_RESOLUTION_INDEPENDANCE`

gemrb/plugins/GAMImporter/GAMImporter.cpp
As reported by https://github.com/gemrb/gemrb/issues/1404#issuecomment-1966478997 PST original crashes again when loading one of our save games. Not sure when it broke but `MakeVariable` removes that critical whitespace from this variable, and the old fix did not do much help anymore.
=> GAMImporter: fixes PST variable special case when saving

gemrb/plugins/AREImporter/AREImporter.cpp
See #2137. 
So ARE1000 has _alternate_ trigger points set (2x 4B) but we did `ReadPoint` that reads 2x 2B. Thus the Y value got lost and trigger points didn't work.
IESDP should maybe be updated, too, since it's both incomplete and doesn't match NI naming.
=> AREImporter fix for IWD2

gemrb/core/Audio.cpp, gemrb/core/Audio.h, gemrb/core/Interface.cpp, gemrb/core/Scriptable/Actor.cpp, gemrb/core/SoundMgr.h, gemrb/plugins/ACMReader/ACMReader.cpp, gemrb/plugins/ACMReader/ACMReader.h, gemrb/plugins/OGGReader/OGGReader.cpp, gemrb/plugins/OGGReader/OGGReader.h, gemrb/plugins/OpenALAudio/OpenALAudio.cpp, gemrb/plugins/OpenALAudio/OpenALAudio.h, gemrb/plugins/WAVReader/WAVReader.cpp, gemrb/plugins/WAVReader/WAVReader.h
Looking at what has been fixed by 95d258a34a9b98f62f13fb4db325f634aa6ad818 and what was haunting me in https://github.com/gemrb/gemrb/issues/2166, I'd like to propose three sound improvements:
1. Walking sounds were not spatial but were vague all over the map, now they are. Unfortunately they are very loud this way compared to other sounds of the same volume setting. That's why I added some multiplier. Feel free to test and compare to the original.
2. Spatial sounds were not rolling off over distance. Now they do over while not turning fully mute technically (that's also a matter of the OpenAL distance model) but you can now hear things coming close and going away depending on the camera/listener's position. That's way more immersive hearing the enemies finding their way and coming …
=> Three sound improvements

.clang-format, .git-blame-ignore-revs, .github/workflows/style.yml, CMakeLists.txt, CONTRIBUTING.md, admin/pre-commit, gemrb/docs/en/CodingStyle.txt, gemrb/includes/CocoaWrapper.h, gemrb/includes/fmt/.clang-format, gemrb/plugins/BIKPlayer/binkdata.h
Started working on #161. I've updated a previous draft to version 17 (just about to be released), but 16 is fine as well.
The rule file is in the commit, while the effect of `clang-format -i gemrb/**/*.[ch] gemrb/**/*.cpp` can be seen here: https://gist.github.com/lynxlynxlynx/87ca0bb6dec4633ef07d4b9a523078a6
As expected some things are not ideal (eg. when to inline functions), but in general it looks ok to me.
TODO:
Infra stuff mentioned in the bug
- use https://github.com/marketplace/actions/c-c-linter disabling tidy and only checking changed lines
- fallback: https://github.com/marketplace/actions/git-clang-format-check-per-commit
- git clang-format, clang-format-diff are shipped with clang
Docs:
=> RFC: added preliminary .clang-format file

gemrb/plugins/GUIScript/GUIScript.cpp
Not sure why it has worked, but it no longer does on my MSYS2 gcc.
=> Fix for `nullptr_t` confusion

gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp
See #2176
- [] The proposed change builds also on our build bots (check after submission)
=> Fix for some bad pixels in TIS sprites

gemrb/core/Logging/Logger.cpp
This pull request attempts to fix an issue I have been encountering with console output, where log statements often fail to get flushed to the console until a subsequent log occurs.
Example of the console window when launching an oBG2 game before / after the fix:
**Before:**
**After:**
=> Logger: Flush after write

gemrb/core/System/VFS.cpp, gemrb/core/System/VFS.h
`DirectoryIterator(DirectoryIterator&&)` failed to take ownership of `DirectoryIterator::Directory`, which without copy elision (debug build) caused `DirectoryIterator::Directory` to be incorrectly closed. I experienced this manifesting as crashes during character creation when importing a character file / when hitting the name stage.
=> DirectoryIterator: Fix move constructor

gemrb/core/GameScript/GSUtils.cpp, gemrb/core/GameScript/GSUtils.h, gemrb/core/GameScript/GameScript.cpp, gemrb/core/GameScript/Objects.cpp, gemrb/core/GameScript/ParseText.cpp, gemrb/core/GameScript/Triggers.cpp, gemrb/unhardcoded/iwd2/script.2da
IWD2 parses object selectors in differing orders depending on whether it's working with .DLG resources (text) or .BCS resources (compiled). It seems that GemRB is using the dialog order to read .BCS files, which causes incorrect object selector resolution in scripts.
Here's the different orders:
- Dialog:
```
[EA.GENERAL.RACE.SUBRACE.CLASS.SPECIFIC.GENDER.ALIGN.AVCLASS.CLASSMSK]
```
- BCS `OB` format:
```
EA GENERAL RACE CLASS SPECIFIC GENDER ALIGNMNT SUBRACE filter1 filter2 filter3 filter4 filter5 [rect1.rect2.rect3.rect4] "scriptname" AVCLASS CLASSMSK
```
I've lightly tested the changes, and am opening this pull request as a draft for feedback as to whether the fix method is acceptable. The PR has softcoded the definition of dialog object selector parsing to `script.2da`.
Some …
=> iwd2: fix object selector value order

demo/override/script.2da, gemrb/unhardcoded/bg1/script.2da, gemrb/unhardcoded/bg2/script.2da, gemrb/unhardcoded/bg2ee/script.2da, gemrb/unhardcoded/how/script.2da, gemrb/unhardcoded/iwd/script.2da, gemrb/unhardcoded/pst/script.2da
Accessing `script.2da`'s `DATA` column by name (introduced in b413f853213b1728c647c1b3e1946c664ddd78c0) caused a regression in parsing the demo's `script.2da`. This PR should fix #2243.
=> Fix demo script.2da

gemrb/core/AmbientMgr.cpp, gemrb/core/Audio.h, gemrb/core/Scriptable/Actor.cpp, gemrb/plugins/NullSound/NullSound.cpp, gemrb/plugins/NullSound/NullSound.h, gemrb/plugins/OGGReader/OGGReader.cpp, gemrb/plugins/OpenALAudio/OpenALAudio.cpp, gemrb/plugins/OpenALAudio/OpenALAudio.h, gemrb/plugins/SDLAudio/SDLAudio.cpp, gemrb/plugins/SDLAudio/SDLAudio.h
Essentially everything sound-related discussed in #2241.
Regarding the volume roll-off of ambients: Good and easy candidates to compare are the crystal in AR1202 of PST, or the buzzing machine very close to where BG2 starts in the dungeon.
It's not that easy and good to directly try to reflect the original since the sound model there is primitive, i. e.  no spatial magic, but more to somewhat get volume levels roughly between the loudest point (center) and the edge before the ambient mgr stops playback due to radius. Can't do too steep roll-off since that would go low too early.
So please have a test and feel free to suggest different params.
=> Some more sound improvements and fixes

gemrb/plugins/OGGReader/OGGReader.cpp, gemrb/plugins/OpenALAudio/OpenALAudio.cpp, gemrb/plugins/OpenALAudio/OpenALAudio.h
I did three things here:
1. OAL: restricted increased source gain to local ambients, globals were measurably too loud this way.
2. OAL: some little refactoring
3. OGG: changed the way samples are counted to match the WAV reading, fixes #2251
=> OGG & OpenAL changes

gemrb/core/GUI/GameControl.cpp, gemrb/core/GUI/GameControl.h, gemrb/plugins/GUIScript/GUIScript.cpp
This pull request allows `ExecuteString()` to use the object under the cursor as the script context, which is a pretty nifty feature lifted from the EE's `Eval()` debug console command.
=> GUIScript: GemRB_ExecuteString() can use object under cursor as script context

cmake/Helpers.cmake
Old check is not sufficient in the new RaspberryPi OS, which can lead to building a broken build, as the default compiler on this OS is currently GCC 12.
Extended file check to additionally look for '/etc/apt/sources.list.d/raspi.list'.
=> Fix detection of RaspberryPi OS

gemrb/core/GUI/WindowManager.cpp
See #2314. I'm aware of PST's `FadeToBlack` and also the opcode 0xC3 as far as it concerns some spells. For the fading, it now matches the original that leaves the UI presented, and the spells also only touch the game world. So is there some case where this wouldn't help or needs more attention?
=> Screen tinting

gemrb/core/GUI/GameControl.cpp, gemrb/core/GUI/GameControl.h, gemrb/core/GUI/GameControlDefs.h
This resolves #2316. Previous behavior is that on pressing an arrow key the viewport would jump in the direction of the arrow key, repeating if key was held down. Diagonal key scrolling did not work. This commit changes to a smooth scroll with diagonal support that matches original IE behavior. Tested with IWD2 and PST.
This is my first PR ever, so any feedback is appreciated. Thanks!
=> GameControl: Implement smooth keyboard scrolling

cmake/Helpers.cmake, platforms/linux/org.gemrb.gemrb.desktop, platforms/linux/org.gemrb.gemrb.metainfo.xml
This change fixes some compliance issues for the AppStream metadata for use on *nix systems. Most of these are not hard requirements as per the FreeDesktop spec, but cause linter errors for e.g. Flatpak builds:
- launcher: Rename `gemrb.desktop` to `org.gemrb.gemrb.desktop` as per [FreeDesktop spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html)
- launcher: Rename `gemrb.png` and `gemrb.svg` to `org.gemrb.gemrb.[svg|png]` to match
- metainfo: Make the `GenericName` and `Comment` in the desktop file a little nicer
- metainfo: Add [developer tag](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer)
- metainfo: Add missing [URL tags](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url) - Flatpak requires …
=> Improve FreeDesktop launcher and metadata files

platforms/linux/org.gemrb.gemrb.metainfo.xml
Flathub recommends the `<summary>` field in metainfo is short and easily understandable - under 35 characters, "Understandable for a non-technical person", "Doesn't repeat the app name" and "Doesn't start with an article". Currently the summary is so long it raises a "Listing Quality" check failure on the listing as a warning, so I've reworded it to fix this.
=> Reword metainfo summary

gemrb/GUIScripts/GUISTORE.py
Issue seen in BG1 (at Jovial Juggler, but would occur at any tavern that provides rumours window). After navigating to rumours window, upon closing the interaction with the relevant NPC the rumours window is still visible, even if it was not the last active window.
Error seen in console:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUISTORE.py", line 203, in <lambda>
[Python/ERROR]:     lambda: ChangeStoreView(OpenStoreRumourWindow),
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUISTORE.py", line 196, in ChangeStoreView
[Python/ERROR]:     return func()
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUICommonWindows.py", line 513, in ret
[Python/ERROR]:     initer(window)
[Python/ERROR]:   File …
```
=> Fixing rumour window dismissal in bg1
