gemrb/gemrb

gemrb/plugins/SDLVideo/SDL20GLVideo.cpp

Something I started to notice only in BG/BG2 is this fisheye effect at the viewport fringe. The OpenGL implementation failed to calculate texture coordinate, so we always squeeze the whole texture instead of clipping it appropriately.

OpenGL: bad clipping calculations

---

gemrb/core/Game.cpp
gemrb/core/Projectile.cpp
gemrb/core/Scriptable/Actor.cpp
gemrb/core/ScriptedAnimation.cpp
gemrb/plugins/SDLVideo/SDL20GLVideo.cpp
gemrb/plugins/SDLVideo/Shaders/SpritePal.glslf
gemrb/plugins/SDLVideo/Shaders/SpritePalGrayed.glslf
gemrb/plugins/SDLVideo/Shaders/SpritePalSepia.glslf

Some more little things fell onto my list, some were regressions or open things from #66 , so please follow the comments below.

Mostly visual fixes 

---

android/prep_env.sh
gemrb.6.in
gemrb/core/SaveGameIterator.cpp
gemrb/core/Scriptable/Actor.cpp
gemrb/docs/en/GUIScript/controls.txt
gemrb/plugins/GUIScript/GUIScript.cpp
gemrb/plugins/OpenALAudio/OpenALAudio.cpp

Hello,
Here is a patch for some spelling issues that the lintian tool reported in the debian gemrb package. I guessed you might be interested.
Cheers,

Fix some spelling issues reported by lintian

---

gemrb/GemRB.cfg.noinstall.sample
gemrb/GemRB.cfg.sample.in

Just to make the ascii art boxes line up.

Expand tabs in sample cfg files

---

gemrb/unhardcoded/bg2/avatars.2da

As requested [here](https://www.gibberlings3.net/forums/topic/30655-werebear-animations-on-gemrb/?tab=comments#comment-272919)

Add _DJ* Werebear animations to avatars.2da

---

gemrb/core/GUI/GameControl.cpp

Fixes the two remaining points from #263 (talk cursor and tooltips).

No cursor change for birds and bats

---

gemrb/GUIScripts/CommonWindow.py
gemrb/GUIScripts/GUIREC.py
gemrb/GUIScripts/GUIRECCommon.py
gemrb/GUIScripts/InventoryCommon.py
gemrb/GUIScripts/iwd2/GUIINV.py

Closes #279, #286, #290, #299, #305.

Subviews: some Python error related GUIScript fixes

---

gemrb/GUIScripts/pst/GUIREC.py

I just recovered what looks the way to go in master. Closes #297

Subviews: fixes GUIREC for PST

---

gemrb/unhardcoded/bg2/avatars.2da

... to match the original. As discussed in #319.

Adjust circle size for Doom_Guard_large anim

---

gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp

Closes #282. Color pickers look like they still have some script issues sometimes, but we address this later.

Subviews: own Sprite surface on copy

---

gemrb/core/Map.h
gemrb/plugins/AREImporter/AREImporter.cpp

See #163, #170.
Please check if we had no misunderstanding here.

AREImporter: saving anim flags in a better way

---

gemrb/plugins/CHUImporter/CHUImporter.cpp

See https://github.com/gemrb/gemrb/commit/3b84fbd21325757f918c84400270b32f67cbb511#r36075612

subviews: make it compile again

---

gemrb/GUIScripts/GUIOPT.py
gemrb/GUIScripts/pst/GUIOPT.py
gemrb/core/GUI/GUIScriptInterface.h

See #434, but this time for the subviews branch.

subviews: prevent saving in exit dialog when there is no game

---

gemrb.6.in

- Update copyright year range
- Link to the gemrb github project instead of SF re. filing issues

Update man page

---

gemrb/core/Scriptable/Actor.cpp
gemrb/plugins/SDLVideo/Shaders/GameSpriteF.glsl

See the two issues discovered in #571 .

subviews: fixes for infravision and OpenGL tinting

---

gemrb/core/GUI/WindowManager.cpp

subviews: increasing the video buffer size for cursors

---

gemrb/plugins/BIKPlayer/BIKPlayer.cpp
gemrb/plugins/BIKPlayer/common.h
gemrb/plugins/BIKPlayer/rational.cpp

See #592; no obvious video glitches yet.

subviews: fix for BIKPlayer breaking builds

---

gemrb/GUIScripts/pst/GUIREC.py

Fix biography selection.

---

gemrb/core/PluginLoader.cpp
gemrb/core/System/VFS.cpp
gemrb/core/System/VFS.h

There were some refactorings that broke how I made it work on master, so this should do it here.

subviews: post-merge fixes for Windows

---

gemrb/core/Scriptable/Actor.cpp
gemrb/docs/en/gemrb_ini.txt

Search for actor sound effects ending with numbers for IWD/HOW

---

gemrb/GemRB.cpp
gemrb/core/GUI/GameControl.cpp
gemrb/core/Region.h
gemrb/includes/win32def.h
gemrb/plugins/GUIScript/GUIScript.cpp
gemrb/plugins/GUIScript/PythonCallbacks.h

Apologies for the mix up yesterday, I only published my experimental branch in order to transfer it to my Raspberry Pi and maybe ask a couple of questions on discord/irc, Using the hints you guys already gave me though, I was able to tidy up some of it which I think should be fine, so I am putting the simple easy stuff up for review.
This fixes 5/7 of the compiler errors that I get from Visual Studio while building subviews. 
I think there's nothing controversial, but if anyone would like, I can give the exact error messages I receive in the build log if need be.
I also tested on Raspbian on my pi4 to check it doesn't break the linux build ( I have to set up a tiny fan to keep the poor thing from melting while doing the build :) )

Subviews tweaks to allow building with MSVC2019

---

gemrb/core/Map.cpp
gemrb/core/Map.h
gemrb/core/PathFinder.cpp
gemrb/core/PathFinder.h

Fixes a couple bugs with the pathfinder and tweaks `Map::FindPath` to provide straighter paths and work faster.
Addresses #871 and #873.

Pathfinder bughunt

---

gemrb/core/Core.cpp
gemrb/core/GUI/GameControl.cpp
gemrb/core/GUI/GameControl.h

Version 4 of the formation and general movement improvements.

(V4) Improve formation movement and right-click moves in general

---

gemrb/core/Map.cpp

Turns out Schedule doesn't actually do anything.

Fix dead code left over by the autopause changes

---

gemrb/GUIScripts/LUCommon.py
gemrb/GUIScripts/LevelUp.py
gemrb/GUIScripts/pst/GUIREC.py

This is nearly finished, but I need to make sure I haven't broken anything
What I have done is further split some of LevelUp.py into different functions, so that I can call them from pst/GUIREC
This allows learning of new spells for TNO, Dakkon and Grace, and as a side effect fixes the skill points given  on multiple level up
What I really need to test is Dual Class still works in BG/BG2, because I am not 100 sure I understand it (see comment)

PST Level up Learn Spells support

---

gemrb/GUIScripts/bg1/GUICG15.py
gemrb/GUIScripts/bg2/GUICG15.py
gemrb/GUIScripts/iwd/CharGen.py

See #1193.
Python lint build error not related to the changes.

GUI: removal of empty slot in racial enemy lists

---

gemrb/core/CharAnimations.cpp
gemrb/core/GameScript/GSUtils.cpp
gemrb/core/Interface.cpp
gemrb/core/Scriptable/Actor.cpp
gemrb/core/Scriptable/Scriptable.cpp
gemrb/plugins/IWDOpcodes/IWDOpcodes.cpp

Confirmed fix as proposed in #1312

Revert of std::stoi over strtol

---

gemrb/core/GUI/GUIAnimation.cpp
gemrb/core/GlobalTimer.cpp
gemrb/core/GlobalTimer.h
gemrb/plugins/GUIScript/GUIScript.cpp

See two issues mentioned in #1314.

Fixes to GUI animations

---

gemrb/core/GameScript/GSUtils.cpp
gemrb/core/Resource.h
gemrb/core/ScriptedAnimation.cpp
gemrb/plugins/FXOpcodes/FXOpcodes.cpp

Fixes some uses of ResRefs causing trouble as mentioned in #1320

Some ResRef cleanups

---

gemrb/core/SaveGameAREExtractor.cpp

Fixing the first save attempt when starting a new game

---

gemrb/core/GUI/GameControl.cpp
gemrb/core/Scriptable/Actor.cpp
gemrb/plugins/BAMImporter/CMakeLists.txt
gemrb/plugins/SDLVideo/SDL20Video.cpp

multiple fixes of bugs and crushes that were faced on a numerous test runs under fedora 34

bug fix x4

---

gemrb/core/CharAnimations.cpp
gemrb/core/Map.cpp
gemrb/core/PluginLoader.cpp
gemrb/core/Projectile.cpp
gemrb/core/System/FileStream.cpp
gemrb/core/System/MemoryStream.cpp
gemrb/core/System/SlicedStream.cpp
gemrb/core/System/SlicedStream.h
gemrb/includes/win32def.h

Bring Windows back to the game. #1389

Making Windows compile again

---

gemrb/plugins/TTFImporter/TTFFontManager.cpp

A simple fix suggestion for #1486.
On Windows, I can now see that many glyphs are missing, a very few on Linux. But this is a different story I suppose.

TTFManager: saving the file data stream for later

---

gemrb/core/GUI/Button.cpp
gemrb/core/GUI/Control.cpp
gemrb/core/GUI/EventMgr.cpp
gemrb/core/GUI/ScrollBar.cpp
gemrb/core/GUI/TextSystem/Font.cpp
gemrb/core/GUI/TextSystem/TextContainer.cpp
gemrb/core/GUI/TextSystem/TextContainer.h
gemrb/core/GUI/Window.cpp
gemrb/core/GUI/WindowManager.cpp
gemrb/core/Game.cpp
gemrb/core/GlobalTimer.cpp
gemrb/core/Interface.cpp
gemrb/core/KeyMap.cpp
gemrb/core/ScriptedAnimation.h
gemrb/core/Video/Video.h
gemrb/plugins/AREImporter/AREImporter.cpp
gemrb/plugins/GUIScript/GUIScript.cpp
gemrb/plugins/IWDOpcodes/IWDOpcodes.cpp
gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h
gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp
gemrb/plugins/SDLVideo/SDLVideo.cpp
platforms/apple/GemRB.xcodeproj/project.pbxproj

Some noticed by Lintian, others noticed while reviewing the fixes.
Signed-off-by: Stephen Kitt <steve@sk2.org>

Typo fixes

---

gemrb/core/Map.cpp

This merge is for simplify #1378

Change to std::sort

---

gemrb/core/System/String.h

Fixes a FTBFS introduced in 3ee3197bf004e2729d2456aaa8ac01672326179c.

Fix missing header

---

gemrb/GUIScripts/bg2/GUIJRNL.py

Added color depending if it is journal or quests.

---

gemrb/core/Animation.cpp

Animation: prevents frame copies if there is nothing to mirror

---

gemrb/core/GUI/ViewInterfaces.h
gemrb/core/GameScript/Actions.cpp
gemrb/core/Scriptable/Actor.cpp
gemrb/core/Strings/CString.h

What was still missing + some minor refactoring to drop another `memcpy` around the code.

MSVC branch fixes

---

gemrb/plugins/SAVImporter/SAVImporter.cpp

SAVImporter: fixes broken lazy ARE lookup

---

gemrb/core/DisplayMessage.h

Fix starting number of the ENUM.

---

gemrb/core/GUI/Console.cpp
gemrb/core/GameScript/Actions.cpp
gemrb/core/GameScript/GSUtils.cpp
gemrb/core/GameScript/GameScript.cpp
gemrb/core/Interface.cpp
gemrb/core/Interface.h
gemrb/core/InterfaceConfig.cpp
gemrb/core/InterfaceConfig.h
gemrb/core/KeyMap.cpp
gemrb/core/Scriptable/Actor.cpp
gemrb/core/Scriptable/Scriptable.cpp
gemrb/core/Streams/DataStream.cpp
gemrb/core/Streams/DataStream.h
gemrb/core/Strings/CString.h
gemrb/core/Strings/String.h
gemrb/core/System/VFS.h
gemrb/includes/StringMap.h
gemrb/plugins/2DAImporter/2DAImporter.cpp
gemrb/plugins/2DAImporter/2DAImporter.h
gemrb/plugins/GUIScript/GUIScript.cpp
gemrb/plugins/IDSImporter/IDSImporter.cpp
gemrb/plugins/INIImporter/INIImporter.cpp
gemrb/plugins/INIImporter/INIImporter.h
gemrb/plugins/MUSImporter/MUSImporter.cpp

This could use more testing/review, and hopefully we have some console commands to help there.
This is some bug fixes/enhancements to some of our string algorithms as well cutting over some C string manipulation to use those algorithms instead so we can be better positioned to finish #1516 at some point.

String explosion

---

.appveyor.yml
platforms/windows/vcpkg.json
platforms/windows/vcpkg_deps.cmake

- Fixed libiconv usage - newer version changed dll name
- Added manifest file for VCPKG, pinned versions to current latest (in case stuff like the above happens again)

- VCPKG using manifest file

---

.gitignore
gemrb/core/Spellbook.cpp

Spellbook Iter fix

---

gemrb/core/Audio.h
gemrb/core/Game.cpp
gemrb/core/Map.cpp
gemrb/core/Map.h
gemrb/core/MapReverb.cpp
gemrb/core/MapReverb.h
gemrb/plugins/AREImporter/AREImporter.cpp
gemrb/plugins/AREImporter/AREImporter.h
gemrb/plugins/OpenALAudio/OpenALAudio.cpp
gemrb/plugins/OpenALAudio/OpenALAudio.h

I dug up my old stash for #1402 and resolved all the conflicts. I still need to find an OpenAL library that supports EFX to test it. I think thats the only reason it sat collecting dust. From what I can tell it looks fine.

Reverb refactor

---

CMakeLists.txt
gemrb/core/CMakeLists.txt
gemrb/core/Core.cpp
gemrb/core/GUI/GameControl.cpp
gemrb/core/GUI/GameControl.h
gemrb/core/GUI/MapControl.cpp
gemrb/core/Geometry.cpp
gemrb/core/Geometry.h
gemrb/core/Light.cpp
gemrb/core/Light.h
gemrb/core/Map.cpp
gemrb/core/Map.h
gemrb/core/Orientation.h
gemrb/core/Polygon.cpp
gemrb/core/Projectile.cpp
gemrb/core/Region.h
gemrb/core/Scriptable/Door.cpp
gemrb/core/Scriptable/Scriptable.cpp
gemrb/core/ScriptedAnimation.cpp
gemrb/core/Video/Video.cpp
gemrb/core/Video/Video.h
gemrb/includes/globals.h
gemrb/plugins/SDLVideo/SDLVideo.cpp
gemrb/plugins/SDLVideo/SDLVideo.h
platforms/apple/GemRB.xcodeproj/project.pbxproj

Mainly this is to add generic Circle/Ellipse plotting and to use these functions in the myriad of places we are creating such shapes.
A couple of things worth mentioning:
1. lights can now be elliptical and the Projectile/ScriptedAnimation code has been updated to use the previously unused `LightY` variable.
2. the circles created for PathFinding are slightly different at larger sizes, but I suspect this is closer to the originals based on existing comments and the fact that the originals certainly would have used something faster than brute force to calculate a circle.

Consolidate Geometry into Geometry.h/cpp

---

gemrb/core/Scriptable/Actor.cpp
gemrb/plugins/FXOpcodes/FXOpcodes.cpp

All forms of haste computed attacks per round way incorrectly, especially combined with other APR modifiers.
> It used to be set in the effect queue, but that doesn't really work as, for one, the fixed APR of most launchers would override it (items come after spells following a reload).  Also the effect sets all those states which are meant to be used elsewhere, so now there's a block late in actor stat refresh code that manually adjusts APR based on those states.
Belm and Kundane didn't work properly with improved haste for the same reason.
It's also after wspatck handler code now, which helps, although because it sets base it would only be wrong by one tick anyway.  (Incidentally, setting base also explains how that code respects the limit of 5 APR despite not calling `ClampStat()`.) …

BG2: Make haste APR bonus work properly by moving it from FXOpcodes to Actor

---

gemrb/GUIScripts/GameCheck.py

See accepted solution in #1735.

GUIScripts: compatibility for WeiDU log file encodings

---

gemrb/plugins/WEDImporter/WEDImporter.cpp

See problem and cause in #1747. Tested all my observations successfully.

WEDImporter: fixing reading the polygons

---

gemrb/plugins/PVRZImporter/PVRZImporter.cpp

See discussion in #1777. Fixes all demonstrated examples.

PVRZImporter: literal type fix

---

CMakeLists.txt

Fast-math fix for GCC/Clang

---

gemrb/core/Interface.cpp

Deferred setup of fog renderer

---

gemrb/core/Cache.h

See https://github.com/gemrb/gemrb/pull/1818#issuecomment-1613298342

Addressing the Sonar complaint in Cache.h

---

.editorconfig

Editorconfig: suppressing automatic whitespace diff noise

---

gemrb/core/Game.h
gemrb/core/GameScript/GSUtils.cpp
gemrb/core/Interface.cpp
gemrb/core/Interface.h
gemrb/core/Scriptable/Actor.cpp
gemrb/core/Scriptable/Scriptable.cpp
gemrb/core/Scriptable/Scriptable.h
gemrb/includes/ie_types.h
gemrb/plugins/FXOpcodes/FXOpcodes.cpp

See https://github.com/gemrb/gemrb/pull/1833#issuecomment-1615828748
@lynxlynxlynx you also mention this https://github.com/gemrb/gemrb/issues/1834#issuecomment-1615855313 but I cannot see this fixed by this, so maybe can you check again or elaborate?

Variables: fix of map type

---

gemrb/core/InterfaceConfig.cpp

Make config keys updatable again

---

gemrb/core/PluginLoader.cpp
gemrb/core/System/VFS.cpp
platforms/vita/dirent.h

See #1847.
You still need buffers in some way for Win API but I guess Sonar and Coverty don't panic anymore.

Refactoring of some `_MAX_PATH` code sections

---

gemrb/core/Scriptable/Actor.cpp

Fix for issue  #1878 create another check if killer is initialized.

Check if killer is initialized.

---

gemrb/core/EnumIndex.h
gemrb/core/GameScript/GSUtils.cpp
gemrb/core/Scriptable/Actor.cpp
gemrb/core/Scriptable/Actor.h
gemrb/plugins/GUIScript/GUIScript.cpp

use EnumArray for Verbal constants

---

gemrb/CMakeLists.txt
gemrb/core/Strings/CString.h
gemrb/plugins/AREImporter/AREImporter.cpp
gemrb/tests/core/Strings/Test_CString.cpp

AREImporter: no more invalid info point resources

---

gemrb/plugins/AREImporter/AREImporter.cpp

AREImporter: dropping an assertion

---

gemrb/core/FontManager.h
gemrb/core/GUI/Button.cpp
gemrb/core/GUI/Button.h
gemrb/core/GUI/Label.cpp
gemrb/core/GUI/Label.h
gemrb/core/GUI/TextArea.cpp
gemrb/core/GUI/TextArea.h
gemrb/core/GUI/TextEdit.cpp
gemrb/core/GUI/TextEdit.h
gemrb/core/GUI/TextSystem/GemMarkup.cpp
gemrb/core/GUI/TextSystem/GemMarkup.h
gemrb/core/GUI/TextSystem/TextContainer.cpp
gemrb/core/GUI/TextSystem/TextContainer.h
gemrb/core/GUI/Tooltip.cpp
gemrb/core/GUI/Tooltip.h
gemrb/core/GUI/View.cpp
gemrb/core/GUI/WorldMapControl.cpp
gemrb/core/GUI/WorldMapControl.h
gemrb/core/Interface.cpp
gemrb/core/Interface.h
gemrb/core/MoviePlayer.h
gemrb/core/TileMap.cpp
gemrb/plugins/BAMImporter/BAMFontManager.cpp
gemrb/plugins/BAMImporter/BAMFontManager.h
gemrb/plugins/CHUImporter/CHUImporter.cpp
gemrb/plugins/GUIScript/GUIScript.cpp
gemrb/plugins/TTFImporter/TTFFontManager.cpp
gemrb/plugins/TTFImporter/TTFFontManager.h
gemrb/unhardcoded/pst/fonts.2da
platforms/apple/CocoaWrapper/mac/CocoaWrapper.mm

Not a refactoring but cleaning up the current Memcheck reports a little.
Addressing #1877, #1901 and #1902.

Some fixes on memory leaks and segfault

---

gemrb/plugins/IWDOpcodes/IWDOpcodes.cpp

IWD monster summoning amount fix

IWD monster summoning amount fix

---

gemrb/core/GameScript/Actions.cpp
gemrb/plugins/FXOpcodes/FXOpcodes.cpp
gemrb/unhardcoded/shared/gemact.ids

[Spells from scrolls issue](https://github.com/gemrb/gemrb/issues/1958)

Fix spells from scrolls

---

gemrb/unhardcoded/pst/avatars.2da

Fix PST blackr.cre (are0301.are) animations

Fix PST Black Rat animations

---

gemrb/core/GameScript/Actions.cpp

for https://github.com/gemrb/gemrb/pull/1962

fix UseItemPoint, parameters cleared after release action

---

gemrb/plugins/KEYImporter/KEYImporter.h

```
/usr/bin/c++ -DHAVE_CONFIG_H -DKEYImporter_EXPORTS -I/wrkdirs/usr/ports/games/gemrb/work/.build -I/wrkdirs/usr/ports/games/gemrb/work/gemrb-0.9.2/gemrb/includes -I/wrkdirs/usr/ports/games/gemrb/work/gemrb-0.9.2/gemrb/core -I/wrkdirs/usr/ports/games/gemrb/work/gemrb-0.9.2/platforms/FreeBSD -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include -Wall -W -Wpointer-arith -pedantic -Wno-format-y2k -Wno-long-long -fsigned-char -fvisibility=hidden -ffast-math -frounding-math -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include  -DNDEBUG -std=gnu++11 -fPIC   -UNDEBUG -MD -MT …
```

Fix build on 32-bit architectures

---

gemrb/core/DisplayMessage.cpp
gemrb/core/DisplayMessage.h
gemrb/core/GameScript/GSUtils.cpp
gemrb/unhardcoded/bg1/colors.2da
gemrb/unhardcoded/bg2/colors.2da
gemrb/unhardcoded/bg2ee/colors.2da
gemrb/unhardcoded/iwd2/colors.2da
gemrb/unhardcoded/pst/colors.2da
gemrb/unhardcoded/shared/colors.2da

unhardcode console colors, fix bg2 party console and dialog color, ref #1982

Console colors fix

---

gemrb/GUIScripts/GUILOAD.py
gemrb/GUIScripts/bg1/GUICG19.py
gemrb/GUIScripts/bg2/GUICG19.py
gemrb/plugins/OpenALAudio/OpenALAudio.cpp
gemrb/plugins/TLKImporter/TLKImporter.cpp

Some things to address #2030, #1993 and apparently something regressed/unfixed after #1715.

Audio improvements/fixes

---

gemrb/GUIScripts/Console.py
gemrb/core/Scriptable/Actor.cpp
gemrb/unhardcoded/bg1/damage.2da
gemrb/unhardcoded/bg2/damage.2da
gemrb/unhardcoded/bg2ee/damage.2da
gemrb/unhardcoded/how/damage.2da
gemrb/unhardcoded/iwd/damage.2da
gemrb/unhardcoded/iwd2/damage.2da
gemrb/unhardcoded/pst/damage.2da

See #2050, and also #2046 as a side node.

Damage animation blending via 2DA

---

cmake/Helpers.cmake

Banning GCC on Raspberry Pi

---

gemrb/GUIScripts/iwd2/CharGen9.py

IWD2: ranger reputation compatibility byte

---

gemrb/core/GUI/View.cpp
gemrb/core/GUI/View.h

Scrollbar performance pt II

---

platforms/windows/CodepageToIconv.h
platforms/windows/CodepageToIconvMap.cpp

See #2106 to have it working again. Will open a follow-up issue for something I noticed.

Windows: Codepage mapping for UTF-8

---

gemrb/GUIScripts/iwd2/CGPortrait.py

IWD2: portrait loop fix

---

gemrb/plugins/CREImporter/CREImporter.cpp

Morale fixes

---

gemrb/unhardcoded/iwd2/stances.2da

See #2156, orc is back and looks like in the original now (slightly focused posture).

Fix animation of IWD2 orcs conjuring spells

---

gemrb/GUIScripts/Container.py
gemrb/core/GUI/GameControl.cpp
gemrb/core/GUI/View.cpp
gemrb/core/GUI/View.h
gemrb/core/GUI/Window.cpp

Container: allowing hotkeys while opened

---

gemrb/core/Map.cpp
gemrb/plugins/CREImporter/CREImporter.cpp
gemrb/plugins/ITMImporter/ITMImporter.cpp

Of #2188 I fixed 3 problems by us (visible in different reports), two things seem to be related to STL and are known issues to show false positives, one looks too complicated and asks for some better solution. I'll open a follow-up.
Still no idea about Windows metrics, will do something if I find out what's wrong, if anything at all.

Memory leak fixes

---

gemrb/core/Scriptable/Actor.cpp

Fix against wrong IE_SANCTUARY value

---

gemrb/core/GameScript/Actions.cpp
gemrb/core/Map.cpp
gemrb/core/Map.h
gemrb/core/PathFinder.cpp
gemrb/core/PathFinder.h
gemrb/core/Projectile.cpp
gemrb/core/Projectile.h
gemrb/core/Scriptable/Actor.cpp
gemrb/core/Scriptable/Scriptable.cpp
gemrb/core/Scriptable/Scriptable.h
gemrb/plugins/GUIScript/GUIScript.cpp

Want some more eyes on these commits, which seem to work fine. So more in the architectural / code sense. The current struct is a minimal implementation for what we were already using.
I also considered moving orientation determination to DoStep, but that was buggy, too much south-facing.
Fixes #880

Upgrade path storage

---

gemrb/core/GUI/TextSystem/Font.cpp
gemrb/core/GUI/TextSystem/Font.h
gemrb/plugins/PVRZImporter/CMakeLists.txt
gemrb/plugins/PVRZImporter/PVRZImporter.cpp
gemrb/plugins/PVRZImporter/PVRZImporter.h
gemrb/tests/PVRZImporter/Test_PVRZImporter.cpp

BAMv2 as font

---

gemrb.6.in

[DOC] Fix malapropism "XDG_CONFIG_PATH"

---

gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp
gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.h

Rarely have so little code lines kept me so busy. Little surprise since only some digging into SDL code made things a little more clear. See #2210 and maybe #2229, but I couldn't reproduce the latter in the same way as described in the issue.

Fixes for some transparency issues

---

gemrb/plugins/GUIScript/GUIScript.cpp

GUIScript: Python crash fix

---

gemrb/GUIScripts/bg1/Start.py

See #2255, MP button disabled, Python error fixed, videos button removed from SP section.
Don't have the classic TotSC right now, so please check if I'm missing something.

BG1 Start cleanup

---

gemrb/plugins/GAMImporter/GAMImporter.cpp

GAMImporter: PST maze data fix

---

gemrb/GUIScripts/GUIDefines.py
gemrb/GUIScripts/GUIOPT.py
gemrb/GUIScripts/pst/Clock.py
gemrb/GUIScripts/pst/GUIOPT.py
gemrb/core/GUI/Tooltip.h
gemrb/core/GUI/WindowManager.cpp
gemrb/core/Interface.cpp
gemrb/core/Interface.h
gemrb/plugins/CREImporter/CREImporter.cpp
gemrb/plugins/GUIScript/GUIScript.cpp

See
* #2281
* #2287
* #2288
* #2310

PST: Some fixes

---

gemrb/plugins/VLCPlayer/VLCPlayer.cpp
gemrb/plugins/VLCPlayer/VLCPlayer.h

VLCPlayer: WebM playback fix

---

gemrb/core/Audio/MusicLoop.cpp
gemrb/plugins/MUSImporter/MUSImporter.cpp

A small collection of fixes and improvements regarding playlists that I encountered while playing. Fixes #2279 but I hope it doesn't break anything else.

Music playlist fixes

---

gemrb/GUIScripts/bg2/Start.py

See #2334. Also the video flags didn't work as expected any more.

BG2 menu: audio & video fixes
